# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# ruff: noqa: D205,D212,D415
r"""
========================
Operator Representations
========================

.. currentmodule:: qiskit_fermions.operators

This module provides various data structures for representing fermionic operators in different
bases.

.. autosummary::
   :toctree: ../stubs/

   OperatorTrait

Fermion Operator
----------------

This operator represents fermionic operators in terms of the second-quantization creation and
annihilation operators.

.. autosummary::
   :toctree: ../stubs/
   :template: autosummary/typealias.rst

   ~fermion_action.FermionAction

.. autosummary::
   :toctree: ../stubs/

   FermionOperator
   cre
   ann

Majorana Operator
-----------------

This operator represents fermionic operators in terms of Majorana fermions.

.. autosummary::
   :toctree: ../stubs/
   :template: autosummary/typealias.rst

   ~majorana_action.MajoranaAction

.. autosummary::
   :toctree: ../stubs/

   MajoranaOperator
   gamma

Interaction Operators
---------------------

Many commonly used operators can be expressed as `interaction` operators which can express operators
with `even fermionic parity`. Such operators are defined in terms of `pairs` of Majorana actions
:math:`\gamma_k\gamma'_k` or, equivalently, are generated by the quadratic fermionic operators
:math:`a_i a_j`, :math:`a_i^\dagger a_j`, :math:`a_i a^\dagger_j`, and :math:`a^\dagger_i
a^\dagger_j`.

This package provides two different data structures expressing operators of this type in terms of
Hermitian generators:

.. autosummary::
   :toctree: ../stubs/
   :template: autosummary/typealias.rst

   ~edge_action.EdgeAction
   ~transfer_action.TransferAction

.. autosummary::
   :toctree: ../stubs/

   EdgeVertexOperator
   TransferVertexOperator

"""

from __future__ import annotations

from qiskit_fermions._lib.operators.edge_vertex_operator import EdgeVertexOperator
from qiskit_fermions._lib.operators.fermion_operator import FermionOperator
from qiskit_fermions._lib.operators.majorana_operator import MajoranaOperator
from qiskit_fermions._lib.operators.transfer_vertex_operator import TransferVertexOperator
from qiskit_fermions.protocols.linear_operator import _linear_operator, _trace

from .edge_action import EdgeAction
from .fermion_action import FermionAction, ann, cre
from .majorana_action import MajoranaAction, gamma
from .operator_trait import OperatorTrait
from .transfer_action import TransferAction

# Attach the ffsim ``_linear_operator_`` and ``_trace_`` protocol methods to the compiled
# ``FermionOperator`` type. They are written in Python because they convert to an
# ``ffsim.FermionOperator``, which the Rust core cannot reach; the compiled type has a writable
# ``__dict__``, so they can be attached here. Only ``FermionOperator`` carries them: the other
# operator types reach the same path by converting through ``_fermion_operator_`` first.
FermionOperator._linear_operator_ = _linear_operator  # type: ignore[attr-defined]
FermionOperator._trace_ = _trace  # type: ignore[attr-defined]

__all__ = [
    "EdgeAction",
    "EdgeVertexOperator",
    "FermionAction",
    "FermionOperator",
    "MajoranaAction",
    "MajoranaOperator",
    "OperatorTrait",
    "TransferAction",
    "TransferVertexOperator",
    "ann",
    "cre",
    "gamma",
]
