# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# ruff: noqa: D205,D212,D415
r"""
========================
Operator Representations
========================

.. currentmodule:: qiskit_fermions.operators

This module provides various data structures for representing fermionic operators in different
bases.

Fermion Operator
----------------

This operator represents fermionic operators in terms of the second-quantization creation and
annihilation operators.

.. autosummary::
   :toctree: ../stubs/
   :template: autosummary/typealias.rst

   ~fermion_action.FermionAction

.. autosummary::
   :toctree: ../stubs/

   FermionOperator
   cre
   ann

Majorana Operator
-----------------

This operator represents fermionic operators in terms of Majorana fermions.

.. autosummary::
   :toctree: ../stubs/
   :template: autosummary/typealias.rst

   ~majorana_action.MajoranaAction

.. autosummary::
   :toctree: ../stubs/

   MajoranaOperator
   gamma

Interaction Operators
---------------------

Many commonly used operators can be expressed as `interaction` operators which can express operators
with `even fermionic parity`. Such operators are defined in terms of `pairs` of Majorana actions
:math:`\gamma_k\gamma'_k` or, equivalently, are generated by the quadratic fermionic operators
:math:`a_i a_j`, :math:`a_i^\dagger a_j`, :math:`a_i a^\dagger_j`, and :math:`a^\dagger_i
a^\dagger_j`.

This package provides two different data structures expressing operators of this type in terms of
Hermitian generators:

.. autosummary::
   :toctree: ../stubs/
   :template: autosummary/typealias.rst

   ~edge_action.EdgeAction
   ~transfer_action.TransferAction

.. autosummary::
   :toctree: ../stubs/

   EdgeVertexOperator
   TransferVertexOperator

Protocol
--------

All operator classes provides by this submodule implement at least those methods specified by the
protocol below:

.. autoclass:: OperatorTrait
   :member-order: bysource
   :show-inheritance:
   :members:
   :exclude-members: __init__, __subclasshook__, __weakref__
   :no-inherited-members:
   :special-members:

"""

from __future__ import annotations

from typing import TYPE_CHECKING

from qiskit_fermions._lib.operators.edge_vertex_operator import (
    EdgeVertexOperator,
)
from qiskit_fermions._lib.operators.fermion_operator import FermionOperator
from qiskit_fermions._lib.operators.majorana_operator import MajoranaOperator
from qiskit_fermions._lib.operators.transfer_vertex_operator import TransferVertexOperator

from .edge_action import EdgeAction
from .fermion_action import FermionAction, ann, cre
from .majorana_action import MajoranaAction, gamma
from .protocol import OperatorTrait
from .transfer_action import TransferAction

if TYPE_CHECKING:
    import scipy.sparse.linalg


def _fermion_operator_linear_operator(  # noqa: D417
    self: FermionOperator, norb: int, nelec: int | tuple[int, int]
) -> scipy.sparse.linalg.LinearOperator:
    """Returns a SciPy ``LinearOperator`` for this operator on the ``(norb, nelec)`` FCI sector.

    This implements ffsim's ``_linear_operator_`` protocol, so a
    :class:`~qiskit_fermions.operators.FermionOperator` can be passed directly to
    :func:`scipy.sparse.linalg.expm_multiply` or to ``ffsim.linear_operator``. It wraps the native
    matrix-vector kernel (:meth:`FermionOperator._fci_linear_operator_`) in a genuine
    :class:`scipy.sparse.linalg.LinearOperator`; ``expm_multiply`` requires the adjoint action, so
    both ``matvec`` and ``rmatvec`` are supplied.

    The native kernel requires a contiguous one-dimensional ``complex128`` vector, whereas SciPy's
    machinery may feed a ``LinearOperator`` real probe vectors (from its one-norm estimator) or
    non-contiguous ``(dim, 1)`` column slices. The ``matvec``/``rmatvec`` wrappers coerce the input
    with ``numpy.ascontiguousarray(v, complex128).reshape(-1)``; the numpy handles are bound once
    here (per operator) rather than re-resolved on every matvec inside the ``expm_multiply`` loop.

    This is attached to :class:`FermionOperator` as ``_linear_operator_`` at import time: the native
    :class:`~qiskit_fermions._lib.operators.fermion_operator.FermionOperator` is a compiled type whose
    instances cannot itself subclass SciPy's ``LinearOperator``, so the protocol method is provided in
    Python.

    Args:
        norb: the number of spatial orbitals.
        nelec: the electron count -- an integer for a spinless sector, or an ``(n_alpha, n_beta)``
            pair for a spinful one.

    Returns:
        A :class:`scipy.sparse.linalg.LinearOperator` applying this operator on the requested sector.
    """
    import numpy as np
    import scipy.sparse.linalg

    kernel = self._fci_linear_operator_(norb, nelec)

    # Bind the coercion handles once per operator (not once per matvec): SciPy hands a
    # LinearOperator real probe vectors or non-contiguous (dim, 1) columns, which the native kernel
    # cannot slice directly.
    ascontiguousarray = np.ascontiguousarray
    complex128 = np.complex128

    def matvec(vec):
        return kernel.matvec(ascontiguousarray(vec, complex128).reshape(-1))

    def rmatvec(vec):
        return kernel.rmatvec(ascontiguousarray(vec, complex128).reshape(-1))

    return scipy.sparse.linalg.LinearOperator(
        shape=kernel.shape,
        matvec=matvec,
        rmatvec=rmatvec,
        dtype=kernel.dtype,
    )


# Attach the ffsim ``_linear_operator_`` protocol method to the compiled ``FermionOperator`` type.
FermionOperator._linear_operator_ = _fermion_operator_linear_operator  # type: ignore[attr-defined]

__all__ = [
    "EdgeAction",
    "EdgeVertexOperator",
    "FermionAction",
    "FermionOperator",
    "MajoranaAction",
    "MajoranaOperator",
    "OperatorTrait",
    "TransferAction",
    "TransferVertexOperator",
    "ann",
    "cre",
    "gamma",
]
