# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
__all__ = [
    "givens_decomposition",
]

def givens_decomposition(unitary: numpy.typing.NDArray[numpy.complex128]) -> tuple[builtins.list[tuple[builtins.float, builtins.complex, builtins.int, builtins.int]], builtins.list[builtins.complex]]:
    r"""
    Decomposes a unitary matrix into Givens rotations and diagonal phases.
    
    The :math:`n \times n` unitary matrix, :math:`U`, can be decomposed into a diagonal matrix,
    :math:`D`, and sequence of :math:`2 \times 2` Givens rotations, :math:`G`, acting on adjacent
    indices. This algorithm [1]_ requires at most :math:`n (n-1) / 2` such Givens rotations.
    
    Each Givens rotation is defined by a 4-tuple, ``(c, s, i, j)``, with:
    
    * ``c``: the real-valued cosine
    * ``s``: the complex-valued sine
    * ``i``: the first row index
    * ``j``: the second row index
    
    which result in a matrix of the form:
    
    .. math::
    
       \begin{pmatrix}
       c & s \\
       -s^\dagger & c
       \end{pmatrix}
    
    Args:
        unitary: the unitary matrix, :math:`U`, to be decomposed.
    
    Returns:
        A 2-tuple consisting of
    
        * the sequence of Givens rotations represented as 4-tuples as explained above
        * the vector of complex phases of the diagonal matrix, :math:`D`
    
    The original unitary is recovered by processing the returned rotations in `reverse` order and
    right-multiplying the diagonal matrix by the `element-wise complex conjugate` of each rotation
    matrix :math:`G_k` (as defined above). That is, for :math:`N` returned rotations,
    
    .. math::
    
       U = D \cdot \overline{G_N} \cdot \overline{G_{N-1}} \cdots \overline{G_1},
    
    where :math:`\overline{G_k}` denotes element-wise conjugation (not the conjugate transpose) and
    each :math:`G_k` acts only on rows/columns :math:`i` and :math:`j` of its rotation.
    
    .. doctest::
    
        >>> import numpy as np
        >>> from qiskit_fermions.linalg import givens_decomposition
        >>> unitary = np.array([[0.6, 0.8j], [0.8, -0.6j]], dtype=complex)
        >>> rotations, phases = givens_decomposition(unitary)
        >>> reconstructed = np.diag(phases).astype(complex)
        >>> for c, s, i, j in rotations[::-1]:
        ...     givens_mat = np.eye(2, dtype=complex)
        ...     givens_mat[np.ix_((i, j), (i, j))] = [[c, s], [-s.conjugate(), c]]
        ...     reconstructed = reconstructed @ givens_mat.conj()
        >>> bool(np.allclose(reconstructed, unitary))
        True
    
    .. [1] W. R. Clements et al., Optimal design for universal multiport interferometers,
           Optica 3, 1460-1465 (2016),
           `doi:10.1364/OPTICA.3.001460 <https://doi.org/10.1364/OPTICA.3.001460>`_.
    """

