# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
from qiskit_fermions._lib.linalg import fci
from qiskit_fermions._lib.operators import majorana_operator
from qiskit_fermions._lib.operators.operators_library import fcidump
import typing
__all__ = [
    "FermionOperator",
    "FermionOperatorDataGroupIter",
    "FermionOperatorDataIter",
]

@typing.final
class FermionOperator:
    r"""
    A spin-less fermionic operator.
    
    Definition
    ==========
    
    This operator is defined by a linear combination of products of fermionic creation and
    annihilation operators acting on spin-less fermionic modes. That is to say, the individual
    terms fulfill the following anti-commutation relations: [1]_
    
    .. math::
    
        \left\{a^\dagger_i, a^\dagger_j\right\} =
        \left\{a_i, a_j\right\} = 0,~~\text{and}~~
        \left\{a_i, a^\dagger_j\right\} = \delta_{ij} \, ,
    
    where :math:`i` and :math:`j` do not distinguish the spin species of the fermionic
    modes they are indexing.
    
    This makes the definition of the entire operator the following:
    
    .. math::
    
       \text{\texttt{FermionOperator}} = \sum_i c_i \bigotimes_j \hat{A_j} \, ,
    
    where :math:`\hat{A_j} \in \{ a_j, a^\dagger_j \}` and :math:`c_i` is the (complex) coefficient
    making up the linear combination of products. The index :math:`j` can take any value between 0
    and the number of fermionic modes acted upon by the operator minus 1.
    
    .. _FermionOperator-implementation:
    
    Implementation
    ==============
    
    This class stores the terms and coefficients in multiple sparse vectors, akin to the
    `compressed sparse row format
    <https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_(CSR,_CRS_or_Yale_format)>`_
    commonly used for sparse matrices. More concretely, a single operator contains 4 arrays:
    
    .. table::
    
       ============== =================================================================================
       ``coeffs``     A vector of complex coefficients consisting of two 64-bit floating point numbers.
       ``actions``    A vector of booleans storing the nature of the second-quantization actions.
       ``modes``      A vector of 32-bit integers storing the fermionic mode indices acted upon.
       ``boundaries`` A vector of integers indicating the boundaries in ``actions`` and ``modes``.
       ============== =================================================================================
    
    Entries in ``actions`` indicate creation (annihilation) operators by ``True`` (``False``).
    Fermionic modes indexed by ``modes`` are considered spinless.
    
    .. note::
       You may access **read-only copies** of these internal arrays via their respective methods:
       :meth:`.get_coeffs`, :meth:`.get_actions`, :meth:`.get_modes`, and :meth:`.get_boundaries`.
    
    This data structure allows for very efficient construction and manipulation of operators.
    However, it implies that duplicate terms may be contained in an operator at any moment.
    These must be resolved manually through the use of :meth:`.simplify`.
    
    Construction
    ------------
    
    An operator can be constructed directly by providing the arrays outlined above:
    
    .. doctest::
    
        >>> from qiskit_fermions.operators import FermionOperator
        >>> coeffs = [1.0, 2.0, -3.0, 4.0j, -0.5j]
        >>> actions = [True, False, False, True, True, True, False, False]
        >>> modes = [0, 0, 0, 1, 0, 1, 2, 3]
        >>> boundaries = [0, 0, 1, 2, 4, 8]
        >>> op = FermionOperator(coeffs, actions, modes, boundaries)
        >>> print(format(op))
          1.000000e0 +0.000000e0j * ()
         -3.000000e0 +0.000000e0j * (-0)
          0.000000e0 +4.000000e0j * (-0 +1)
          2.000000e0 +0.000000e0j * (+0)
         -0.000000e0-5.000000e-1j * (+0 +1 -2 -3)
    
    For convenience, it is possible to construct an operator from a Python dictionary like so:
    
    .. doctest::
    
        >>> from qiskit_fermions.operators import cre, ann
        >>> op = FermionOperator.from_dict(
        ...     {
        ...         (): 1.0,
        ...         (cre(0),): 2.0,
        ...         (ann(0),): -3.0,
        ...         (ann(0), cre(1)): 4.0j,
        ...         (cre(0), cre(1), ann(2), ann(3)): -0.5j,
        ...     }
        ... )
        >>> print(format(op))
          1.000000e0 +0.000000e0j * ()
         -3.000000e0 +0.000000e0j * (-0)
          0.000000e0 +4.000000e0j * (-0 +1)
          2.000000e0 +0.000000e0j * (+0)
         -0.000000e0-5.000000e-1j * (+0 +1 -2 -3)
    
    In this example, we have leveraged :func:`.cre` and :func:`.ann` for creating the creation and
    annihilation operators at the specified modes.
    
    In addition, the following construction and quick helper methods are available:
    
    .. autosummary::
    
       zero
       one
       from_terms
       from_terms_with_groups
    
    Formatting
    ----------
    
    In the examples above, the constructed operators have been printed using the output from
    :py:func:`format`, which results in a human-readable form of the operator.
    
    .. doctest::
    
        >>> print(format(op))
          1.000000e0 +0.000000e0j * ()
         -3.000000e0 +0.000000e0j * (-0)
          0.000000e0 +4.000000e0j * (-0 +1)
          2.000000e0 +0.000000e0j * (+0)
         -0.000000e0-5.000000e-1j * (+0 +1 -2 -3)
    
    .. note::
       The printing order of ``format(op)`` gets explicitly sorted before printing. As such, it
       does not reflect the order of the terms inside the operator.
    
    An alternative form can be obtained from the :py:func:`repr` function, which results in a
    Python-interpretable representation. In other words, this output can readily be copied and
    pasted into a Python shell:
    
    .. doctest::
    
        >>> print(repr(op))
        FermionOperator.from_dict({...})
    
    Finally, for large operators both of these outputs may be very long and undesirable. Then, a
    very simple form with minimal information can be obtained from the :py:func:`str` function:
    
    .. doctest::
    
        >>> print(str(op))
        <FermionOperator with 5 terms>
    
    Iteration
    ---------
    
    Since the underlying data structure is implemented in Rust and has a non-trivial layout, it
    cannot be iterated over directly:
    
    .. doctest::
    
        >>> list(iter(op))
        Traceback (most recent call last):
          ...
        TypeError: 'qiskit_fermions.operators.fermion_operator.FermionOperator' object is not iterable
    
    Instead, this class provides custom iterators to fulfill this purpose:
    
    .. doctest::
    
        >>> list(sorted(op.iter_terms()))
        [([], (1+0j)), ([(False, 0)], (-3+0j)), ([(False, 0), (True, 1)], 4j), ([(True, 0)], (2+0j)), ([(True, 0), (True, 1), (False, 2), (False, 3)], (-0-0.5j))]
    
    See also:
        :meth:`iter_terms`
            For more relevant implementation details.
    
    The table below lists all available iterators:
    
    .. autosummary::
    
       iter_terms
       iter_terms_with_groups
    
    Arithmetics
    -----------
    
    The following arithmetic operations are supported:
    
    Addition/Subtraction
    ^^^^^^^^^^^^^^^^^^^^
    
    .. doctest::
    
        >>> op = FermionOperator.one()
        >>> (op + op).simplify()
        FermionOperator.from_dict({(): 2+0j})
        >>> (op - op).simplify()
        FermionOperator.from_dict({})
        >>> op += op
        >>> op.simplify()
        FermionOperator.from_dict({(): 2+0j})
        >>> op -= op
        >>> op.simplify()
        FermionOperator.from_dict({})
    
    Scalar Multiplication/Divison
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    .. doctest::
    
        >>> op = FermionOperator.one()
        >>> (2 * op).simplify()
        FermionOperator.from_dict({(): 2+0j})
        >>> (op / 2).simplify()
        FermionOperator.from_dict({(): 0.5+0j})
        >>> op *= 2
        >>> op.simplify()
        FermionOperator.from_dict({(): 2+0j})
        >>> op /= 2
        >>> op.simplify()
        FermionOperator.from_dict({(): 1+0j})
    
    Operator Composition
    ^^^^^^^^^^^^^^^^^^^^
    
    .. note::
       Operator composition corresponds to left-multiplication: ``c = a & b`` corresponds to
       :math:`C = B A`. In other words, the composition of two operators returns a resulting
       operator that performs "first ``a`` and then ``b``".
    
    .. doctest::
    
        >>> op1 = FermionOperator.from_dict({(): 2.0, (cre(0),): 3.0})
        >>> op2 = FermionOperator.from_dict({(): 1.5, (ann(1),): 4.0})
        >>> comp = (op1 & op2).simplify()
        >>> print(format(comp))
          3.000000e0 +0.000000e0j * ()
          8.000000e0 +0.000000e0j * (-1)
          1.200000e1 +0.000000e0j * (-1 +0)
          4.500000e0 +0.000000e0j * (+0)
        >>> op2 &= op1
        >>> print(format(op2.simplify()))
          3.000000e0 +0.000000e0j * ()
          8.000000e0 +0.000000e0j * (-1)
          4.500000e0 +0.000000e0j * (+0)
          1.200000e1 +0.000000e0j * (+0 -1)
        >>> squared = (op1 ** 2).simplify()
        >>> print(format(squared))
          4.000000e0 +0.000000e0j * ()
          1.200000e1 +0.000000e0j * (+0)
          9.000000e0 +0.000000e0j * (+0 +0)
    
    .. note::
       For convenience, the right-multiplication is implemented by ``c = a @ b`` (resulting in
       :math:`C = A B`).
    
    .. doctest::
    
        >>> (op1 @ op2).equiv(op2 & op1)
        True
    
    Other Operations
    ^^^^^^^^^^^^^^^^
    
    In addition to the magic methods that correspond to the arithmetic operations outlined above,
    the following methods are available:
    
    .. autosummary::
    
       adjoint
       ichop
       simplify
       normal_ordered
       relabel_modes
    
    Properties
    ^^^^^^^^^^
    
    Finally, various methods exist to check certain properties of an operator:
    
    .. autosummary::
    
       is_hermitian
       max_rank
       conserves_particle_number
    
    .. [1] https://en.wikipedia.org/wiki/Second_quantization#Fermion_creation_and_annihilation_operators
    """
    @property
    def groups(self) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        An optional vector of `group indices` for each term.
        
        For more information refer to the :mod:`~qiskit_fermions.operators.terms.grouping` module.
        """
    @groups.setter
    def groups(self, value: typing.Optional[typing.Sequence[builtins.int]]) -> None:
        r"""
        Sets the :attr:`groups` attribute.
        """
    def _majorana_operator_(self) -> majorana_operator.MajoranaOperator:
        r"""
        Converts this operator into a :class:`.MajoranaOperator`.
        
        This implements the :class:`.SupportsMajoranaOperator` protocol by delegating to
        :func:`.fermion_to_majorana`.
        """
    def __add__(self, other: FermionOperator) -> FermionOperator: ...
    def __iadd__(self, other: FermionOperator) -> None: ...
    def __sub__(self, other: FermionOperator) -> FermionOperator: ...
    def __isub__(self, other: FermionOperator) -> None: ...
    def __mul__(self, other: builtins.complex) -> FermionOperator: ...
    def __rmul__(self, other: builtins.complex) -> FermionOperator: ...
    def __imul__(self, other: builtins.complex) -> None: ...
    def __truediv__(self, other: builtins.complex) -> FermionOperator: ...
    def __itruediv__(self, other: builtins.complex) -> None: ...
    def __neg__(self) -> FermionOperator: ...
    def __and__(self, other: FermionOperator) -> FermionOperator: ...
    def __iand__(self, other: FermionOperator) -> None: ...
    def __matmul__(self, other: FermionOperator) -> FermionOperator: ...
    def __imatmul__(self, other: FermionOperator) -> None: ...
    def __len__(self) -> builtins.int: ...
    def __deepcopy__(self, _memo: typing.Any) -> FermionOperator: ...
    def __pow__(self, exponent: builtins.int, modulo: typing.Optional[builtins.int] = None) -> FermionOperator: ...
    def __str__(self) -> builtins.str: ...
    def __new__(cls, coeffs: typing.Sequence[builtins.complex], actions: typing.Sequence[builtins.bool], modes: typing.Sequence[builtins.int], boundaries: typing.Sequence[builtins.int]) -> FermionOperator: ...
    @classmethod
    def from_dict(cls, data: typing.Mapping[typing.Sequence[tuple[builtins.bool, builtins.int]], builtins.complex]) -> FermionOperator:
        r"""
        Constructs a new operator from a dictionary.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict(
            ...     {
            ...         (): 1.0-1.0j,
            ...         ((True, 0), (False, 1)): 2.0,
            ...     }
            ... )
            >>> print(format(op))
              1.000000e0 -1.000000e0j * ()
              2.000000e0 +0.000000e0j * (+0 -1)
        
        Args:
            data: a dictionary mapping tuples of terms to complex coefficients. Each key is a tuple
                of ``(bool, int)`` pairs. You may use :func:`.cre` and :func:`.ann` to simplify
                their construction.
        
        Returns:
            A new operator.
        """
    def get_coeffs(self) -> builtins.list[builtins.complex]:
        r"""
        Returns a read-only list of the operator's coefficients.
        
        .. note::
           This method returns a **copy** of the internal data.
        
        .. seealso::
           The explanation of the internal data structure,
           :ref:`here <FermionOperator-implementation>`.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.one()
            >>> op += -1j * FermionOperator.one()
            >>> op.get_coeffs()
            [(1+0j), -1j]
        
        Returns:
            A list of the operator's coefficients.
        """
    def get_actions(self) -> builtins.list[builtins.bool]:
        r"""
        Returns a read-only list of the operator's actions.
        
        .. note::
           This method returns a **copy** of the internal data.
        
        .. seealso::
           The explanation of the internal data structure,
           :ref:`here <FermionOperator-implementation>`.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.one()
            >>> op += FermionOperator.from_dict({((True, 0), (False, 1)): 1.0})
            >>> op.get_actions()
            [True, False]
        
        Returns:
            A list of the operator's actions.
        """
    def get_modes(self) -> builtins.list[builtins.int]:
        r"""
        Returns a read-only list of the operator's acted-upon mode indices.
        
        .. note::
           This method returns a **copy** of the internal data.
        
        .. seealso::
           The explanation of the internal data structure,
           :ref:`here <FermionOperator-implementation>`.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.one()
            >>> op += FermionOperator.from_dict({((True, 0), (False, 1)): 1.0})
            >>> op.get_modes()
            [0, 1]
        
        Returns:
            A list of the operator's modes.
        """
    def get_boundaries(self) -> builtins.list[builtins.int]:
        r"""
        Returns a read-only list of the indices indicating the boundaries between operator terms.
        
        .. note::
           This method returns a **copy** of the internal data.
        
        .. seealso::
           The explanation of the internal data structure,
           :ref:`here <FermionOperator-implementation>`.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.one()
            >>> op += FermionOperator.from_dict({((True, 0), (False, 1)): 1.0})
            >>> op.get_boundaries()
            [0, 0, 2]
        
        Returns:
            A list of the operator's terms boundaries.
        """
    def get_support(self) -> builtins.set[builtins.int]:
        r"""
        Returns the set of mode indices which this operator acts upon.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict(
            ...     {
            ...         ((True, 0), (False, 4)): 1,
            ...         ((True, 1), (True, 3), (False, 4), (False, 7)): 1,
            ...     }
            ... )
            >>> assert op.get_support() == {0, 1, 3, 4, 7}
        
        Returns:
            The set of mode indices which this operator acts upon.
        """
    def __richcmp__(self, other: FermionOperator, op: int) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...
    def __format__(self, _format_spec: builtins.str) -> builtins.str: ...
    @classmethod
    def zero(cls) -> FermionOperator:
        r"""
        Constructs the additive identity operator.
        
        Adding the operator that is constructed by this method to another one has no effect.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({(): 2.0})
            >>> zero = FermionOperator.zero()
            >>> op + zero == op
            True
        
        ..
        """
    @classmethod
    def one(cls) -> FermionOperator:
        r"""
        Constructs the multiplicative identity operator.
        
        Composing the operator that is constructed by this method with another one has no effect.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({(): 2.0})
            >>> one = FermionOperator.one()
            >>> op & one == op
            True
        
        ..
        """
    def simplify(self, atol: builtins.float = 1e-08) -> FermionOperator:
        r"""
        Returns an equivalent but simplified operator.
        
        The simplification process first sums all coefficients that belong to equal terms and then
        only retains those whose total coefficient exceeds the specified tolerance (just like
        :meth:`.ichop`).
        
        When an operator has been arithmetically manipulated or constructed in a way that does not
        guarantee unique terms, this method should be called before applying any method that
        filters numerically small coefficients to avoid loss of information. See the example below
        which showcases how :meth:`.ichop` can truncate terms that sum to a total coefficient
        magnitude which should not be truncated:
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> coeffs = [1e-5] * int(1e5)
            >>> boundaries = [0] + [0] * int(1e5)
            >>> op = FermionOperator(coeffs, [], [], boundaries)
            >>> canon = op.simplify(1e-4)
            >>> assert canon.equiv(op.one(), 1e-6)
            >>> op.ichop(1e-4)
            >>> assert op.equiv(op.zero(), 1e-6)
        
        Args:
            atol: the absolute tolerance for the cutoff. This value defaults to ``1e-8``.
        
        Returns:
            An equivalent but simplified operator.
        """
    def ichop(self, atol: builtins.float = 1e-08) -> None:
        r"""
        Removes terms whose coefficient magnitude lies below the provided threshold.
        
        This method modifies the operator *in place* and returns ``None``.
        
        .. caution::
           This method truncates coefficients greedily! If the acted upon operator may contain
           separate coefficients for duplicate terms consider calling :meth:`.simplify` instead!
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({(): 1e-4, ((True, 0),): 1e-6, ((False, 0),): 1e-10})
            >>> print(format(op))
              1.000000e-4 +0.000000e0j * ()
             1.000000e-10 +0.000000e0j * (-0)
              1.000000e-6 +0.000000e0j * (+0)
            >>> op.ichop()
            >>> print(format(op))
              1.000000e-4 +0.000000e0j * ()
              1.000000e-6 +0.000000e0j * (+0)
            >>> op.ichop(1e-5)
            >>> print(format(op))
              1.000000e-4 +0.000000e0j * ()
        
        Args:
            atol: the absolute tolerance for the cutoff. This value defaults to ``1e-8``.
        """
    def iter_terms(self) -> FermionOperatorDataIter:
        r"""
        An iterator over the operator's terms.
        
        .. warning::
           Mutating the iteration items does **not** affect the underlying operator data.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({(): 2.0, ((True, 0),): 1.0, ((False, 1),): -1.0j})
            >>> list(sorted(op.iter_terms()))
            [([], (2+0j)), ([(False, 1)], (-0-1j)), ([(True, 0)], (1+0j))]
        
        ..
        """
    @classmethod
    def from_terms(cls, terms: typing.Any) -> FermionOperator:
        r"""
        Constructs a new operator from an iterator of terms (see also :meth:`.iter_terms`).
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({(): 2.0, ((True, 0),): 1.0, ((False, 1),): -1.0j})
            >>> op.equiv(FermionOperator.from_terms(op.iter_terms()))
            True
        
        Args:
            terms: an iterator of terms as produced by :meth:`.iter_terms`.
        
        Returns:
            A new operator.
        """
    def iter_terms_with_groups(self) -> FermionOperatorDataGroupIter:
        r"""
        An iterator over the operator's terms with their associated group index.
        
        .. warning::
           Mutating the iteration items does **not** affect the underlying operator data.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator(
            ...     [2.0, 1.0, -1.0],
            ...     [True, False, True, False],
            ...     [0, 1, 1, 0],
            ...     [0, 0, 2, 4],
            ... )
            >>> op.groups = [0, 1, 1]
            >>> list(sorted(op.iter_terms_with_groups()))
            [([], (2+0j), 0), ([(True, 0), (False, 1)], (1+0j), 1), ([(True, 1), (False, 0)], (-1+0j), 1)]
        
        ..
        """
    @classmethod
    def from_terms_with_groups(cls, terms: typing.Any) -> FermionOperator:
        r"""
        Constructs a new operator from an iterator of terms with groups (see also
        :meth:`.iter_terms_with_groups`).
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator(
            ...     [2.0, 1.0, -1.0],
            ...     [True, False, True, False],
            ...     [0, 1, 1, 0],
            ...     [0, 0, 2, 4],
            ... )
            >>> op.groups = [0, 1, 1]
            >>> reconstructed = FermionOperator.from_terms_with_groups(op.iter_terms_with_groups())
            >>> op.equiv(reconstructed) and op.groups == reconstructed.groups
            True
        
        Args:
            terms: an iterator of terms as produced by :meth:`.iter_terms_with_groups`.
        
        Returns:
            A new operator.
        """
    def has_groups(self) -> builtins.bool:
        r"""
        Returns whether this operator tracks group indices.
        
        This is equivalent to (but cheaper than) checking ``op.groups is not None``, because it does
        not copy the group indices out of the operator in order to inspect them.
        
        .. note::
           This returns ``True`` even when :attr:`groups` is an empty list, which is the state of a
           grouped operator that holds no terms.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator(
            ...     [1.0, 2.0, -1.0, -2.0],
            ...     [True, False, True, False, True, False, True, False],
            ...     [0, 1, 2, 3, 1, 0, 3, 2],
            ...     [0, 2, 4, 6, 8],
            ... )
            >>> op.has_groups()
            False
            >>> op.groups = [0, 1, 0, 1]
            >>> op.has_groups()
            True
        
        Returns:
            Whether :attr:`groups` is set on this operator.
        """
    def num_groups(self) -> typing.Optional[builtins.int]:
        r"""
        Returns the number of groups.
        
        If :attr:`groups` is ``None``, this function also returns ``None``. Otherwise, it will
        return the number of groups which is defined to be the largest occurring group index plus
        1 (which may therefore be used as the index for the next group).
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator(
            ...     [1.0, 2.0, -1.0, -2.0],
            ...     [True, False, True, False, True, False, True, False],
            ...     [0, 1, 2, 3, 1, 0, 3, 2],
            ...     [0, 2, 4, 6, 8],
            ... )
            >>> op.groups = [0, 1, 0, 1]
            >>> op.num_groups()
            2
        
        Returns:
            The largest group index in :attr:`groups` plus 1.
        """
    def group_weights(self) -> typing.Optional[builtins.list[builtins.float]]:
        r"""
        Returns the mean absolute coefficient magnitude of each group.
        
        The ``i``-th entry is the sum of ``abs(coeff)`` over the terms in group ``i``, divided by
        the number of terms in that group. If :attr:`groups` is ``None``, this function also returns
        ``None``.
        
        This is the sampling weight of a randomized product formula (e.g. qDRIFT) that draws whole
        groups rather than individual terms. Computing it natively is considerably cheaper than
        reducing :meth:`get_coeffs` and :attr:`groups` in NumPy, because those two accessors each
        copy one value per *ungrouped* term out of the operator only for it to be aggregated back
        down to one value per group, whereas this returns just the :meth:`num_groups` reduced
        values.
        
        .. note::
           A group index that no term carries weighs ``0.0``, which keeps it out of the sample.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator(
            ...     [1.0, 2.0, -1.0, -2.0],
            ...     [True, False, True, False, True, False, True, False],
            ...     [0, 1, 2, 3, 1, 0, 3, 2],
            ...     [0, 2, 4, 6, 8],
            ... )
            >>> print(op.group_weights())
            None
            >>> op.groups = [0, 1, 0, 1]
            >>> op.group_weights()
            [1.0, 2.0]
        
        Returns:
            The mean absolute coefficient magnitude of each group index.
        """
    def split_out_groups(self, group_indices: typing.Optional[typing.Sequence[builtins.int]] = None) -> typing.Optional[builtins.list[FermionOperator]]:
        r"""
        Splits this operator into an optional list of new operators based on :attr:`groups`.
        
        If :attr:`groups` is ``None``, this function also returns ``None``. Otherwise, if
        ``group_indices`` is ``None`` (the default), it returns a list of one new operator for
        every group index in :attr:`groups`, in index order. If ``group_indices`` is given, only
        the requested indices are built, in the given order: this avoids the cost of constructing
        operators for groups that are never used, which is especially beneficial when only a small
        number of groups out of a much larger total are needed, e.g. when subsampling groups for a
        randomized product formula. A duplicate index in ``group_indices`` is returned once per
        occurrence.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator(
            ...     [1.0, 2.0, -1.0, -2.0],
            ...     [True, False, True, False, True, False, True, False],
            ...     [0, 1, 2, 3, 1, 0, 3, 2],
            ...     [0, 2, 4, 6, 8],
            ... )
            >>> print(op.split_out_groups())
            None
            >>> op.groups = [0, 1, 0, 1]
            >>> groups = op.split_out_groups()
            >>> for g in groups:
            ...     print(list(sorted(g.iter_terms())))
            [([(True, 0), (False, 1)], (1+0j)), ([(True, 1), (False, 0)], (-1+0j))]
            [([(True, 2), (False, 3)], (2+0j)), ([(True, 3), (False, 2)], (-2+0j))]
            >>> groups = op.split_out_groups(group_indices=[1])
            >>> for g in groups:
            ...     print(list(sorted(g.iter_terms())))
            [([(True, 2), (False, 3)], (2+0j)), ([(True, 3), (False, 2)], (-2+0j))]
        
        Args:
            group_indices: the group indices for which to build operators, in the desired output
                order. When omitted, every group is built, in index order.
        
        Returns:
            An optional vector of one new operator for each requested group index.
        """
    def adjoint(self) -> FermionOperator:
        r"""
        Returns the Hermitian conjugate (or adjoint) of this operator.
        
        This affects the terms and coefficients as follows:
        
        - the actions in each term reverse their order and flip between creation and annihilation
        - the coefficients are complex conjugated
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({(): -1.0j, ((True, 0), (False, 1)): 1.0})
            >>> adj = op.adjoint()
            >>> print(format(adj))
             -0.000000e0 +1.000000e0j * ()
              1.000000e0 -0.000000e0j * (+1 -0)
        
        ..
        """
    def equiv(self, other: FermionOperator, atol: builtins.float = 1e-08) -> builtins.bool:
        r"""
        Checks this operator for equivalence with another operator.
        
        Equivalence in this context means approximate equality up to the specified absolute
        tolerance. To be more precise, this method returns ``True``, when all the absolute values
        of the coefficients in the difference ``other - self`` are below the specified threshold
        ``atol``.
        
        .. note::
           This is the mathematical comparison you almost always want. It differs from the ``==``
           operator, which tests exact equality of the *stored* terms (their coefficients, actions,
           modes, and internal term boundaries) with no tolerance and no simplification. Two
           mathematically equal operators can therefore compare unequal under ``==`` if they are
           stored differently -- for example an unsimplified ``a + a`` versus ``2 * a``, or terms
           held in a different order. Use ``equiv`` to compare operators up to numerical tolerance.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({(): 1e-7})
            >>> zero = FermionOperator.zero()
            >>> op.equiv(zero)
            False
            >>> op.equiv(zero, 1e-6)
            True
            >>> op.equiv(zero, 1e-9)
            False
        
        Args:
            other: the other operator to compare with.
            atol: the absolute tolerance for the comparison. This value defaults to ``1e-8``.
        """
    def normal_ordered(self, sandwich: typing.Optional[builtins.bool] = None) -> FermionOperator:
        r"""
        Returns an equivalent operator with normal ordered terms.
        
        The normal order of an operator term is defined such that all creation actions appear
        before all annihilation actions.
        Within each group, the acted-upon modes are ordered lexicographically. Whether their order
        is ascending or descending depends upon the value of the ``sandwich`` argument:
        
        - ``None`` (default): both groups are ordered lexicographically descending (e.g.
          ``+1 +0 -1 -0``)
        - ``True``: larger indices appear towards the middle, i.e. creation actions are
          lexicographically ascending while annihilation ones are descending (e.g.
          ``+0 +1 -1 -0``)
        - ``False``: smaller indices appear towards the middle, i.e. creation actions are
          lexicographically descending while annihilation ones are ascending (e.g.
          ``+1 +0 -0 -1``)
        
        .. note::
           When a term is being reordered, the anti-commutation relations have to be taken into
           account, :math:`a_i a^\dagger_j = \delta_{ij} - a^\dagger_j a^i`, implying that the
           number of terms may change.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({((False, 1), (True, 1), (False, 0), (True, 0)): 1})
            >>> print(format(op.normal_ordered().simplify()))
              1.000000e0 +0.000000e0j * ()
             -1.000000e0 +0.000000e0j * (+0 -0)
             -1.000000e0 +0.000000e0j * (+1 -1)
             -1.000000e0 +0.000000e0j * (+1 +0 -1 -0)
            >>> print(format(op.normal_ordered(sandwich=True).simplify()))
              1.000000e0 +0.000000e0j * ()
             -1.000000e0 +0.000000e0j * (+0 -0)
              1.000000e0 +0.000000e0j * (+0 +1 -1 -0)
             -1.000000e0 +0.000000e0j * (+1 -1)
            >>> print(format(op.normal_ordered(sandwich=False).simplify()))
              1.000000e0 +0.000000e0j * ()
             -1.000000e0 +0.000000e0j * (+0 -0)
             -1.000000e0 +0.000000e0j * (+1 -1)
              1.000000e0 +0.000000e0j * (+1 +0 -0 -1)
        
        Returns:
            An equivalent but normal-ordered operator.
        """
    def is_hermitian(self, atol: builtins.float = 1e-08) -> builtins.bool:
        r"""
        Returns whether this operator is Hermitian.
        
        .. note::
           This check is implemented using :meth:`.equiv` on the :meth:`.normal_ordered` difference
           of ``self`` and its :meth:`.adjoint` and :meth:`.zero`.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({
            ...     ((True, 0), (False, 1)): 1.00001j,
            ...     ((True, 1), (False, 0)): -1j,
            ... })
            >>> op.is_hermitian()
            False
            >>> op.is_hermitian(1e-4)
            True
        
        Args:
            atol: The numerical accuracy upto which coefficients are considered equal. This value
                defaults to ``1e-8``.
        
        Returns:
            Whether this operator is Hermitian.
        """
    def max_rank(self) -> builtins.int:
        r"""
        Returns the maximum rank of the terms in this operator.
        
        .. note::
           The length of the longest term can depend on the operator's form which means that (for
           example) operator simplification or normal-ordering can result in a different maximum
           rank.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({
            ...     ((True, 0), (False, 1), (True, 2), (False, 3)): 1,
            ... })
            >>> op.max_rank()
            4
        
        Returns:
            The maximum rank of this operator.
        """
    def conserves_particle_number(self) -> builtins.bool:
        r"""
        Returns whether this operator is particle-number conserving.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({((True, 0), (False, 1)): 1})
            >>> op.conserves_particle_number()
            True
            >>> op = FermionOperator.from_dict({((True, 0),): 1})
            >>> op.conserves_particle_number()
            False
        
        Returns:
            Whether this operator is particle-number conserving.
        """
    def conserves_sector(self, block_sizes: typing.Sequence[builtins.int]) -> builtins.bool:
        r"""
        Returns whether every term conserves particle number within each mode block.
        
        ``block_sizes`` partitions the mode range into consecutive, non-overlapping blocks: block
        ``b`` spans modes ``[start_b, start_b + block_sizes[b])`` where ``start_b`` is the sum of the
        preceding block sizes. A term conserves the sector if and only if, in *every* block, its
        number of creation operators equals its number of annihilation operators. A term acting on a
        mode beyond the final block does not conserve the sector.
        
        An empty ``block_sizes`` treats all modes as a single block, making this equivalent to
        :meth:`conserves_particle_number`. A single block ``[norb]`` checks conservation for a
        spinless FCI sector, while two equal blocks ``[norb, norb]`` check that the alpha modes
        ``[0, norb)`` and beta modes ``[norb, 2 * norb)`` are each conserved -- i.e. conservation of
        both particle number and the z-component of spin.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({((True, 0), (False, 2)): 1})
            >>> op.conserves_sector([4])  # one spinless block of 4 orbitals
            True
            >>> op.conserves_sector([2, 2])  # moves a particle from the alpha block to the beta block
            False
        
        Args:
            block_sizes: the sizes of the consecutive mode blocks that each must be conserved.
        
        Returns:
            Whether every term conserves particle number within each mode block.
        """
    def relabel_modes(self, permutation: typing.Sequence[builtins.int]) -> FermionOperator:
        r"""
        Returns a new operator with relabeled modes.
        
        .. doctest::
        
            >>> from qiskit_fermions.operators import FermionOperator
            >>> op = FermionOperator.from_dict({
            ...     ((True, 0), (False, 1)): 1,
            ...     ((True, 0), (False, 1), (True, 2), (False, 3)): 1,
            ... })
            >>> permutation = [5, 6, 4, 3]
            >>> relabeled = op.relabel_modes(permutation)
            >>> print(format(relabeled))
              1.000000e0 +0.000000e0j * (+5 -6)
              1.000000e0 +0.000000e0j * (+5 -6 +4 -3)
        
        Args:
            permutation: the index permutation list. Mode ``i`` is relabeled to ``permutation[i]``,
                so the list must contain no duplicate entries and must be long enough to index every
                mode the operator acts upon (its length must exceed the operator's largest mode
                index).
        
        Returns:
            A new operator with its modes relabeled.
        
        Raises:
            ValueError: if ``permutation`` contains duplicate entries, or is too short to relabel
                some mode the operator acts upon.
        """
    def __getnewargs__(self) -> tuple[builtins.list[builtins.complex], builtins.list[builtins.bool], builtins.list[builtins.int], builtins.list[builtins.int]]:
        r"""
        Returns a native FCI matrix-vector view of this operator on a fixed sector.
        
        This is the native kernel carrier behind the public ``_linear_operator_`` protocol method:
        it applies this operator to a state vector via a native matrix-vector kernel, avoiding any
        conversion to an intermediate representation. The returned object duck-types the subset of
        the SciPy ``LinearOperator`` interface that :func:`scipy.sparse.linalg.expm_multiply` needs,
        but it is **not** itself a SciPy ``LinearOperator``. The public ``_linear_operator_`` method
        (added in Python, see :mod:`qiskit_fermions.operators`) wraps this into a genuine
        :class:`scipy.sparse.linalg.LinearOperator` -- which is what ffsim's ``_linear_operator_``
        protocol (and :external:func:`ffsim.linear_operator`) require.
        
        The FCI sector is selected by ``nelec``:
        
        * an ``int`` treats the operator's ``norb`` modes as spinless orbitals; the state vector has
          length :math:`\binom{norb}{nelec}`.
        * a ``(n_alpha, n_beta)`` tuple treats the operator's ``2 * norb`` modes as spin-orbitals
          under the block-spin convention; the state vector has length
          :math:`\binom{norb}{n_\alpha} \binom{norb}{n_\beta}`.
        
        Args:
            norb: the number of (spatial) orbitals.
            nelec: the electron count -- an ``int`` for a spinless sector, or a ``(n_alpha, n_beta)``
                tuple for a spinful one.
        
        Returns:
            A native ``LinearOperator``-compatible object for the requested sector.
        
        Raises:
            TypeError: if ``nelec`` is neither an ``int`` nor a ``(int, int)`` tuple.
            ValueError: if ``norb`` exceeds the maximum number of orbitals the bitmask
                representation supports (64).
        Returns the constructor arguments needed to pickle this operator.
        
        Together with :meth:`__getstate__`/:meth:`__setstate__` (which round-trip
        :attr:`groups`), this makes instances of this class picklable.
        """
    def __getstate__(self) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        Returns the pickled state of this operator (its :attr:`groups`).
        """
    def __setstate__(self, state: typing.Optional[typing.Sequence[builtins.int]]) -> None:
        r"""
        Restores this operator's :attr:`groups` from its pickled state.
        """
    def _fci_linear_operator_(self, norb: builtins.int, nelec: typing.Any) -> fci.FciLinearOperator: ...
    @staticmethod
    def _commutator_(op_a: FermionOperator, op_b: FermionOperator) -> FermionOperator: ...
    @staticmethod
    def _anti_commutator_(op_a: FermionOperator, op_b: FermionOperator) -> FermionOperator: ...
    @staticmethod
    def _double_commutator_(op_a: FermionOperator, op_b: FermionOperator, op_c: FermionOperator, sign: builtins.bool) -> FermionOperator: ...
    @classmethod
    def from_1body_tril_spin_sym(cls, one_body_a: numpy.typing.NDArray[numpy.float64], norb: builtins.int) -> FermionOperator:
        r"""
        Constructs an operator from spin-symmetric triangular 1-body integrals.
        
        The resulting operator is defined by
        
        .. math::
        
            \sum_i c^\alpha_{ii} (a^\dagger_i a_i + a^\dagger_{i+n} a_{i+n}) +
            \sum_{i \lt j} c^\alpha_{ij} (a^\dagger_i a_j + a^\dagger_j a_i +
                                          a^\dagger_{i+n} a_{j+n} + a^\dagger_{j+n} a_{i+n})
        
        where :math:`c^\alpha` are the integral coefficients stored in ``one_body_a``, :math:`i`
        and :math:`j` are the indices expanded from the triangular index :math:`ij` which indexes
        the array, and :math:`n` is the number of orbitals, ``norb``.
        
        The resulting operator acts on :math:`2n` spin-less fermionic modes in block-spin ordering:
        modes :math:`0, \dots, n-1` are the :math:`\alpha`-spin orbitals and modes
        :math:`n, \dots, 2n-1` are the :math:`\beta`-spin orbitals (so orbital :math:`i` of the
        :math:`\beta`-spin species is mode :math:`i+n`).
        
        .. doctest::
        
           >>> import numpy as np
           >>> from qiskit_fermions.operators import FermionOperator
           >>> one_body_a = np.array([1.0, 2.0, 3.0])
           >>> op = FermionOperator.from_1body_tril_spin_sym(one_body_a, norb=2)
           >>> print(format(op))
             1.000000e0 +0.000000e0j * (+0 -0)
             2.000000e0 +0.000000e0j * (+0 -1)
             2.000000e0 +0.000000e0j * (+1 -0)
             3.000000e0 +0.000000e0j * (+1 -1)
             1.000000e0 +0.000000e0j * (+2 -2)
             2.000000e0 +0.000000e0j * (+2 -3)
             2.000000e0 +0.000000e0j * (+3 -2)
             3.000000e0 +0.000000e0j * (+3 -3)
        
        Args:
            one_body_a: a 1-dimensional array of length :math:`n * (n + 1) / 2` storing the 1-body
                electronic integral coefficients of the :math:`\alpha`-spin species, as a flattened
                triangular matrix.
            norb: the number of orbitals, :math:`n`.
        
        Returns:
            The 1-body component of the electronic structure Hamiltonian as defined above.
        ..
        """
    @classmethod
    def from_1body_tril_spin(cls, one_body_a: numpy.typing.NDArray[numpy.float64], one_body_b: numpy.typing.NDArray[numpy.float64], norb: builtins.int) -> FermionOperator:
        r"""
        Constructs an operator from separate spin-species triangular 1-body integrals.
        
        The resulting operator is defined by
        
        .. math::
        
            \sum_i c^\alpha_{ii} a^\dagger_i a_i + c^\beta_{ii} a^\dagger_{i+n} a_{i+n} +
            \sum_{i \lt j} c^\alpha_{ij} (a^\dagger_i a_j + a^\dagger_j a_i) +
                           c^\beta_{ij} (a^\dagger_{i+n} a_{j+n} + a^\dagger_{j+n} a_{i+n})
        
        where :math:`c^\alpha` (:math:`c^\beta`) are the integral coefficients stored in
        ``one_body_a`` (``one_body_b``, resp.), :math:`i` and :math:`j` are the indices expanded
        from the triangular index :math:`ij` which indexes the arrays, and :math:`n` is the number
        of orbitals, ``norb``.
        
        The resulting operator acts on :math:`2n` spin-less fermionic modes in block-spin ordering:
        modes :math:`0, \dots, n-1` are the :math:`\alpha`-spin orbitals and modes
        :math:`n, \dots, 2n-1` are the :math:`\beta`-spin orbitals (so orbital :math:`i` of the
        :math:`\beta`-spin species is mode :math:`i+n`).
        
        .. doctest::
        
           >>> import numpy as np
           >>> from qiskit_fermions.operators import FermionOperator
           >>> one_body_a = np.array([1.0, 2.0, 3.0])
           >>> one_body_b = np.array([-1.0, -2.0, -3.0])
           >>> op = FermionOperator.from_1body_tril_spin(one_body_a, one_body_b, norb=2)
           >>> print(format(op))
             1.000000e0 +0.000000e0j * (+0 -0)
             2.000000e0 +0.000000e0j * (+0 -1)
             2.000000e0 +0.000000e0j * (+1 -0)
             3.000000e0 +0.000000e0j * (+1 -1)
            -1.000000e0 +0.000000e0j * (+2 -2)
            -2.000000e0 +0.000000e0j * (+2 -3)
            -2.000000e0 +0.000000e0j * (+3 -2)
            -3.000000e0 +0.000000e0j * (+3 -3)
        
        Args:
            one_body_a: a 1-dimensional array of length :math:`n * (n + 1) / 2` storing the 1-body
                electronic integral coefficients of the :math:`\alpha`-spin species, as a flattened
                triangular matrix.
            one_body_b: a 1-dimensional array of length :math:`n * (n + 1) / 2` storing the 1-body
                electronic integral coefficients of the :math:`\beta`-spin species, as a flattened
                triangular matrix.
            norb: the number of orbitals, :math:`n`.
        
        Returns:
            The 1-body component of the electronic structure Hamiltonian as defined above.
        ..
        """
    @classmethod
    def from_2body_tril_spin_sym(cls, two_body_aa: numpy.typing.NDArray[numpy.float64], norb: builtins.int) -> FermionOperator:
        r"""
        Constructs an operator from spin-symmetric triangular 2-body integrals.
        
        The resulting operator is defined by
        
        .. math::
        
            \sum_{ijkl} \frac{1}{2} c^{\alpha\alpha}_{ijkl}
                \sum_{(i,j,k,l) \in \mathcal{P}(ijkl)}
                    (a^\dagger_i a^\dagger_k a_l a_j +
                     a^\dagger_{i+n} a^\dagger_k a_l a_{j+n} +
                     a^\dagger_i a^\dagger_{k+n} a_{l+n} a_j +
                     a^\dagger_{i+n} a^\dagger_{k+n} a_{l+n} a_{j+n})
        
        where :math:`c^{\alpha\alpha}` are the integral coefficients stored in ``two_body_aa``,
        :math:`ijkl` is the running index of the array, :math:`\mathcal{P}` generates the unique
        permutations of the 4-index :math:`(i,j,k,l)` (see below), and :math:`n` is the number of
        orbitals, ``norb``.
        
        The two-body coefficients are expected in `chemist` ordering, :math:`(ij|kl)`, i.e. the two
        index pairs :math:`(i,j)` and :math:`(k,l)` each label a charge density. The factor of
        :math:`\frac{1}{2}` is the conventional two-body prefactor.
        
        The resulting operator acts on :math:`2n` spin-less fermionic modes in block-spin ordering:
        modes :math:`0, \dots, n-1` are the :math:`\alpha`-spin orbitals and modes
        :math:`n, \dots, 2n-1` are the :math:`\beta`-spin orbitals (so orbital :math:`i` of the
        :math:`\beta`-spin species is mode :math:`i+n`).
        
        .. note::
            ``two_body_aa`` is an S8-fold symmetric array. That means, it is the flattened
            lower-triangular data of a matrix of shape ``(npair, npair)``, where
            ``npair = (norb * (norb + 1) // 2``. This in turn is the lower-triangular data of the
            4-dimensional array of shape ``(norb, norb, norb, norb)``.
            Therefore, :math:`\mathcal{P}` above expands the flattened index :math:`ijkl` into all
            index permutations :math:`(i,j,k,l)` that index this 4-dimensional array.
        
        .. doctest::
        
           >>> import numpy as np
           >>> from qiskit_fermions.operators import FermionOperator
           >>> two_body_aa = np.arange(1, 7, dtype=float)
           >>> op = FermionOperator.from_2body_tril_spin_sym(two_body_aa, norb=2)
           >>> len(op)
           64
        
        Args:
            two_body_aa: a 1-dimensional array of the S8-fold symmetric 2-body electronic integral
                coefficients of the :math:`\alpha\alpha`-spin species, as a flattened array.
            norb: the number of orbitals, :math:`n`.
        
        Returns:
            The 2-body component of the electronic structure Hamiltonian as defined above.
        ..
        """
    @classmethod
    def from_2body_tril_spin(cls, two_body_aa: numpy.typing.NDArray[numpy.float64], two_body_ab: numpy.typing.NDArray[numpy.float64], two_body_bb: numpy.typing.NDArray[numpy.float64], norb: builtins.int) -> FermionOperator:
        r"""
        Constructs an operator from separate spin-species triangular 2-body integrals.
        
        The resulting operator is defined by
        
        .. math::
        
            \sum_{ijkl} \frac{1}{2}
                \sum_{(i,j,k,l) \in \mathcal{P}(ijkl)}
                    c^{\alpha\alpha}_{ijkl} a^\dagger_i a^\dagger_k a_l a_j +
                    c^{\beta\beta}_{ijkl} a^\dagger_{i+n} a^\dagger_{k+n} a_{l+n} a_{j+n}
            + \sum_{ijkl} \frac{1}{2}
                \sum_{(i,j,k,l) \in \mathcal{P'}(ijkl)}
                    c^{\alpha\beta}_{ijkl} a^\dagger_{i+n} a^\dagger_k a_l a_{j+n} +
                    c^{\alpha\beta}_{ijkl} a^\dagger_i a^\dagger_{k+n} a_{l+n} a_j +
        
        where :math:`c^{\alpha\alpha}` (:math:`c^{\alpha\beta}`, :math:`c^{\beta\beta}`) are the
        integral coefficients stored in ``two_body_aa`` (``two_body_ab``, ``two_body_bb``, resp.),
        :math:`ijkl` is the running index of the array, :math:`\mathcal{P}` (:math:`\mathcal{P'}`)
        generates the unique permutations of the 4-index :math:`(i,j,k,l)` (see below), and
        :math:`n` is the number of orbitals, ``norb``.
        
        The two-body coefficients are expected in `chemist` ordering, :math:`(ij|kl)`, i.e. the two
        index pairs :math:`(i,j)` and :math:`(k,l)` each label a charge density. The factor of
        :math:`\frac{1}{2}` is the conventional two-body prefactor.
        
        The resulting operator acts on :math:`2n` spin-less fermionic modes in block-spin ordering:
        modes :math:`0, \dots, n-1` are the :math:`\alpha`-spin orbitals and modes
        :math:`n, \dots, 2n-1` are the :math:`\beta`-spin orbitals (so orbital :math:`i` of the
        :math:`\beta`-spin species is mode :math:`i+n`).
        
        .. note::
            ``two_body_aa`` and ``two_body_bb`` are a S8-fold symmetric arrays. That means, they
            are the flattened lower-triangular data of matrices of shape ``(npair, npair)``, where
            ``npair = (norb * (norb + 1) // 2``. These in turn are the lower-triangular data of the
            4-dimensional arrays of shape ``(norb, norb, norb, norb)``.
            Therefore, :math:`\mathcal{P}` above expands the flattened index :math:`ijkl` into all
            index permutations :math:`(i,j,k,l)` that index these 4-dimensional arrays.
        
            However, ``two_body_ab`` is only S4-fold symmetric. Thus, it contains the full data of
            the ``(npair, npair)`` matrix (but still in flattened form). :math:`\mathcal{P'}`
            performs the corresponding index expansion. (In the definition above, we reused the
            index :math:`ijkl` as an abuse of notation.)
        
        .. doctest::
        
           >>> import numpy as np
           >>> from qiskit_fermions.operators import FermionOperator
           >>> two_body_aa = np.arange(1, 7, dtype=float)
           >>> two_body_ab = np.arange(11, 20, dtype=float)
           >>> two_body_bb = np.arange(-1, -7, -1, dtype=float)
           >>> op = FermionOperator.from_2body_tril_spin(two_body_aa, two_body_ab, two_body_bb, norb=2)
           >>> len(op)
           64
        
        Args:
            two_body_aa: a 1-dimensional array of the S8-fold symmetric 2-body electronic integral
                coefficients of the :math:`\alpha\alpha`-spin species, as a flattened array.
            two_body_ab: a 1-dimensional array of the S4-fold symmetric 2-body electronic integral
                coefficients of the :math:`\alpha\beta`-spin species, as a flattened array.
            two_body_bb: a 1-dimensional array of the S8-fold symmetric 2-body electronic integral
                coefficients of the :math:`\beta\beta`-spin species, as a flattened array.
            norb: the number of orbitals, :math:`n`.
        
        Returns:
            The 2-body component of the electronic structure Hamiltonian as defined above.
        ..
        """
    @classmethod
    def from_fcidump(cls, fcidump: fcidump.FCIDump) -> FermionOperator:
        r"""
        Constructs a :class:`.FermionOperator` from an :class:`.FCIDump` data structure.
        
        Assuming you have an FCIDump file called ``molecule.fcidump``, you can construct the
        second-quantized operator like so:
        
        .. code-block:: python
        
           from qiskit_fermions.operators import FermionOperator
           from qiskit_fermions.operators.library import FCIDump
        
           fcidump = FCIDump.from_file("molecule.fcidump")
           operator = FermionOperator.from_fcidump(fcidump)
        
        Args:
            fcidump: the FCIDump data structure.
        
        Returns:
            The constructed operator. When the FCIDump provides a constant (e.g. nuclear-repulsion)
            energy, it is included as the identity term ``()``.
        """

@typing.final
class FermionOperatorDataGroupIter:
    def __iter__(self) -> FermionOperatorDataGroupIter: ...
    def __next__(self) -> tuple[list[tuple[bool, int]], complex, int]: ...

@typing.final
class FermionOperatorDataIter:
    def __iter__(self) -> FermionOperatorDataIter: ...
    def __next__(self) -> tuple[list[tuple[bool, int]], complex]: ...

