// This code is a Qiskit project.
//
// (C) Copyright IBM 2026.
//
// This code is licensed under the Apache License, Version 2.0. You may
// obtain a copy of this license in the LICENSE.txt file in the root directory
// of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.

#include "common.h"
#include <qiskit_fermions.h>
#include <stdint.h>
#include <stdio.h>
#include <stdnoreturn.h>

static int test_ferm_op_commutator(void) {
    QfFermionOperator *op1 = qf_ferm_op_zero();
    QkComplex64 coeff1 = {1.0, 0.0};
    bool action1[2] = {true, false};
    uint32_t indices1[2] = {0, 0};
    qf_ferm_op_add_term(op1, 2, action1, indices1, &coeff1);
    QfFermionOperator *op2 = qf_ferm_op_zero();
    QkComplex64 coeff2 = {2.0, 0.0};
    bool action2[2] = {false, true};
    uint32_t indices2[2] = {0, 0};
    qf_ferm_op_add_term(op2, 2, action2, indices2, &coeff2);

    QfFermionOperator *comm = qf_ferm_op_commutator(op1, op2);

    QfFermionOperator *normal = qf_ferm_op_normal_ordered(comm, NULL);
    QfFermionOperator *canon = qf_ferm_op_simplify(normal, 1e-8);

    qf_ferm_op_ichop(canon, 1e-8);

    QfFermionOperator *zero = qf_ferm_op_zero();
    bool is_equal = qf_ferm_op_equal(canon, zero);

    qf_ferm_op_free(op1);
    qf_ferm_op_free(op2);
    qf_ferm_op_free(zero);

    if (!is_equal) {
        return EqualityError;
    }
    return Ok;
}

static int test_ferm_op_anti_commutator(void) {
    QfFermionOperator *op1 = qf_ferm_op_zero();
    QkComplex64 coeff1 = {1.0, 0.0};
    bool action1[2] = {true, false};
    uint32_t indices1[2] = {0, 0};
    qf_ferm_op_add_term(op1, 2, action1, indices1, &coeff1);
    QfFermionOperator *op2 = qf_ferm_op_zero();
    QkComplex64 coeff2 = {2.0, 0.0};
    bool action2[2] = {false, true};
    uint32_t indices2[2] = {0, 0};
    qf_ferm_op_add_term(op2, 2, action2, indices2, &coeff2);

    QfFermionOperator *anti_comm = qf_ferm_op_anti_commutator(op1, op2);

    QfFermionOperator *normal = qf_ferm_op_normal_ordered(anti_comm, NULL);
    QfFermionOperator *canon = qf_ferm_op_simplify(normal, 1e-8);

    qf_ferm_op_ichop(canon, 1e-8);

    QfFermionOperator *zero = qf_ferm_op_zero();
    bool is_equal = qf_ferm_op_equal(canon, zero);

    qf_ferm_op_free(op1);
    qf_ferm_op_free(op2);
    qf_ferm_op_free(zero);

    if (!is_equal) {
        return EqualityError;
    }
    return Ok;
}

static int test_ferm_op_double_commutator(void) {
    QfFermionOperator *op1 = qf_ferm_op_zero();
    QkComplex64 coeff1 = {1.0, 0.0};
    bool action1[2] = {true, false};
    uint32_t indices1[2] = {0, 0};
    qf_ferm_op_add_term(op1, 2, action1, indices1, &coeff1);
    QfFermionOperator *op2 = qf_ferm_op_zero();
    QkComplex64 coeff2 = {2.0, 0.0};
    bool action2[2] = {false, true};
    uint32_t indices2[2] = {0, 0};
    qf_ferm_op_add_term(op2, 2, action2, indices2, &coeff2);
    QfFermionOperator *op3 = qf_ferm_op_zero();
    qf_ferm_op_add_term(op3, 2, action1, indices1, &coeff1);
    QkComplex64 coeff3 = {2.0, 0.5};
    qf_ferm_op_add_term(op3, 2, action2, indices2, &coeff3);

    QfFermionOperator *double_comm = qf_ferm_op_double_commutator(op1, op2, op3, false);

    QfFermionOperator *normal = qf_ferm_op_normal_ordered(double_comm, NULL);
    QfFermionOperator *canon = qf_ferm_op_simplify(normal, 1e-8);

    qf_ferm_op_ichop(canon, 1e-8);

    QfFermionOperator *zero = qf_ferm_op_zero();
    bool is_equal = qf_ferm_op_equal(canon, zero);

    qf_ferm_op_free(op1);
    qf_ferm_op_free(op2);
    qf_ferm_op_free(zero);

    if (!is_equal) {
        return EqualityError;
    }
    return Ok;
}

// Builds a small two-term Majorana operator `c0 * gamma_{m00} gamma_{m01} + c1 * gamma_{m10}`.
// The helper keeps the three majorana commutator subtests below readable.
static QfMajoranaOperator *maj_op_build(QkComplex64 c0, uint32_t m00, uint32_t m01, QkComplex64 c1,
                                        uint32_t m10) {
    QfMajoranaOperator *op = qf_maj_op_zero();
    uint32_t modes0[2] = {m00, m01};
    qf_maj_op_add_term(op, 2, modes0, &c0);
    uint32_t modes1[1] = {m10};
    qf_maj_op_add_term(op, 1, modes1, &c1);
    return op;
}

// The three majorana commutator variants are generated by the same macro as the fermion ones but
// have no C-level test. Rather than hard-code the algebra, each subtest below reconstructs the
// expected result from the documented definition using the compose/add/scalar-mul primitives and
// checks equivalence -- this exercises the C entry point (name mangling, boxing) while remaining a
// genuine correctness check.

// -1 scalar, used to subtract operators (there is no dedicated `sub`, so we add a negated copy).
static const QkComplex64 MINUS_ONE = {-1.0, 0.0};

static int test_maj_op_commutator(void) {
    QkComplex64 c1 = {1.0, 0.0}, c2 = {0.0, 2.0};
    QfMajoranaOperator *op1 = maj_op_build(c1, 0, 1, c2, 2);
    QfMajoranaOperator *op2 = maj_op_build(c2, 1, 2, c1, 0);

    QfMajoranaOperator *result = qf_maj_op_commutator(op1, op2);

    // Reference: [A, B] = A@B - B@A.
    QfMajoranaOperator *ab = qf_maj_op_compose(op1, op2);
    QfMajoranaOperator *ba = qf_maj_op_compose(op2, op1);
    QfMajoranaOperator *neg_ba = qf_maj_op_mul(ba, &MINUS_ONE);
    QfMajoranaOperator *expected = qf_maj_op_add(ab, neg_ba);

    bool is_equiv = qf_maj_op_equiv(result, expected, 1e-10);

    qf_maj_op_free(op1);
    qf_maj_op_free(op2);
    qf_maj_op_free(result);
    qf_maj_op_free(ab);
    qf_maj_op_free(ba);
    qf_maj_op_free(neg_ba);
    qf_maj_op_free(expected);

    if (!is_equiv) {
        return EqualityError;
    }
    return Ok;
}

static int test_maj_op_anti_commutator(void) {
    QkComplex64 c1 = {1.0, 0.0}, c2 = {0.0, 2.0};
    QfMajoranaOperator *op1 = maj_op_build(c1, 0, 1, c2, 2);
    QfMajoranaOperator *op2 = maj_op_build(c2, 1, 2, c1, 0);

    QfMajoranaOperator *result = qf_maj_op_anti_commutator(op1, op2);

    // Reference: {A, B} = A@B + B@A.
    QfMajoranaOperator *ab = qf_maj_op_compose(op1, op2);
    QfMajoranaOperator *ba = qf_maj_op_compose(op2, op1);
    QfMajoranaOperator *expected = qf_maj_op_add(ab, ba);

    bool is_equiv = qf_maj_op_equiv(result, expected, 1e-10);

    qf_maj_op_free(op1);
    qf_maj_op_free(op2);
    qf_maj_op_free(result);
    qf_maj_op_free(ab);
    qf_maj_op_free(ba);
    qf_maj_op_free(expected);

    if (!is_equiv) {
        return EqualityError;
    }
    return Ok;
}

// Reconstructs the exact symmetric double commutator from its definition, mirroring
// `double_commutator` in crates/core/src/operators/library/commutators.rs. Exercises both `sign`
// branches (untested for majorana), each of which selects sign_num = +1 (true) or -1 (false).
static int test_maj_op_double_commutator_identity(bool sign) {
    QkComplex64 c1 = {1.0, 0.0}, c2 = {0.0, 2.0};
    QfMajoranaOperator *op_a = maj_op_build(c1, 0, 1, c2, 2);
    QfMajoranaOperator *op_b = maj_op_build(c2, 1, 2, c1, 0);
    QfMajoranaOperator *op_c = maj_op_build(c1, 2, 3, c2, 1);

    QfMajoranaOperator *result = qf_maj_op_double_commutator(op_a, op_b, op_c, sign);

    const QkComplex64 sign_num = sign ? (QkComplex64){1.0, 0.0} : (QkComplex64){-1.0, 0.0};
    const QkComplex64 HALF = {0.5, 0.0};

    // Pairwise products.
    QfMajoranaOperator *ab = qf_maj_op_compose(op_a, op_b);
    QfMajoranaOperator *ba = qf_maj_op_compose(op_b, op_a);
    QfMajoranaOperator *ac = qf_maj_op_compose(op_a, op_c);
    QfMajoranaOperator *ca = qf_maj_op_compose(op_c, op_a);

    // Triple products (matching the associativity used in the reference).
    QfMajoranaOperator *abc = qf_maj_op_compose(ab, op_c);
    QfMajoranaOperator *cab = qf_maj_op_compose(op_c, ab);
    QfMajoranaOperator *bac = qf_maj_op_compose(ba, op_c);
    QfMajoranaOperator *cba = qf_maj_op_compose(op_c, ba);
    QfMajoranaOperator *acb = qf_maj_op_compose(ac, op_b);
    QfMajoranaOperator *bca = qf_maj_op_compose(op_b, ca);

    // term1 = abc - sign_num * cba
    QfMajoranaOperator *cba_s = qf_maj_op_mul(cba, &sign_num);
    QfMajoranaOperator *neg_cba_s = qf_maj_op_mul(cba_s, &MINUS_ONE);
    QfMajoranaOperator *term1 = qf_maj_op_add(abc, neg_cba_s);

    // term2 = -bac + sign_num * cab
    QfMajoranaOperator *neg_bac = qf_maj_op_mul(bac, &MINUS_ONE);
    QfMajoranaOperator *cab_s = qf_maj_op_mul(cab, &sign_num);
    QfMajoranaOperator *term2 = qf_maj_op_add(neg_bac, cab_s);

    // term3 = acb + sign_num * bca
    QfMajoranaOperator *bca_s = qf_maj_op_mul(bca, &sign_num);
    QfMajoranaOperator *term3 = qf_maj_op_add(acb, bca_s);

    // diff = term2 - term3
    QfMajoranaOperator *neg_term3 = qf_maj_op_mul(term3, &MINUS_ONE);
    QfMajoranaOperator *diff = qf_maj_op_add(term2, neg_term3);

    // expected = term1 + 0.5 * diff
    QfMajoranaOperator *half_diff = qf_maj_op_mul(diff, &HALF);
    QfMajoranaOperator *expected = qf_maj_op_add(term1, half_diff);

    bool is_equiv = qf_maj_op_equiv(result, expected, 1e-10);

    QfMajoranaOperator *to_free[] = {op_a,  op_b,      op_c,  result,    ab,      ba,    ac,
                                     ca,    abc,       cab,   bac,       cba,     acb,   bca,
                                     cba_s, neg_cba_s, term1, neg_bac,   cab_s,   term2, bca_s,
                                     term3, neg_term3, diff,  half_diff, expected};
    for (size_t i = 0; i < sizeof(to_free) / sizeof(to_free[0]); i++) {
        qf_maj_op_free(to_free[i]);
    }

    if (!is_equiv) {
        return EqualityError;
    }
    return Ok;
}

static int test_maj_op_double_commutator_sign_true(void) {
    return test_maj_op_double_commutator_identity(true);
}

static int test_maj_op_double_commutator_sign_false(void) {
    return test_maj_op_double_commutator_identity(false);
}

int test_commutators(void) {
    int num_failed = 0;
    num_failed += RUN_TEST(test_ferm_op_commutator);
    num_failed += RUN_TEST(test_ferm_op_anti_commutator);
    num_failed += RUN_TEST(test_ferm_op_double_commutator);
    num_failed += RUN_TEST(test_maj_op_commutator);
    num_failed += RUN_TEST(test_maj_op_anti_commutator);
    num_failed += RUN_TEST(test_maj_op_double_commutator_sign_true);
    num_failed += RUN_TEST(test_maj_op_double_commutator_sign_false);

    fflush(stderr);
    fprintf(stderr, "=== Number of failed subtests: %i\n", num_failed);

    return num_failed;
}
