# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from qiskit_fermions._lib.operators import edge_vertex_operator
from qiskit_fermions._lib.operators import fermion_operator
from qiskit_fermions._lib.operators import majorana_operator
__all__ = [
    "edge_vertex_to_fermion",
    "edge_vertex_to_majorana",
]

def edge_vertex_to_fermion(inter_op: edge_vertex_operator.EdgeVertexOperator) -> fermion_operator.FermionOperator:
    r"""
    Map an :class:`.EdgeVertexOperator` to a :class:`.FermionOperator`.
    
    Args:
        inter_op: the edge-vertex operator to map.
    
    Returns:
        The mapped fermionic operator.
    
    Definition
    ==========
    
    This function decomposes the edge-vertex operators in terms of the fermionic action operators
    as defined :ref:`here <EdgeVertexOperator-definition>`.
    
    Usage
    =====
    
    .. doctest::
    
        >>> from qiskit_fermions.mappers.library import edge_vertex_to_fermion
        >>> from qiskit_fermions.operators import EdgeVertexOperator
        >>> inter_op = EdgeVertexOperator.from_dict({((0, 0),): 1, ((1, 2),): 2})
        >>> fer_op = edge_vertex_to_fermion(inter_op)
        >>> print(format(fer_op.normal_ordered().simplify()))
          1.000000e0 +0.000000e0j * ()
         -0.000000e0 +2.000000e0j * (-2 -1)
         -2.000000e0 +0.000000e0j * (+0 -0)
          0.000000e0 -2.000000e0j * (+1 -2)
         -0.000000e0 +2.000000e0j * (+2 -1)
         -0.000000e0 +2.000000e0j * (+2 +1)
    
    ..
    """

def edge_vertex_to_majorana(inter_op: edge_vertex_operator.EdgeVertexOperator) -> majorana_operator.MajoranaOperator:
    r"""
    Map an :class:`.EdgeVertexOperator` to a :class:`.MajoranaOperator`.
    
    Args:
        inter_op: the edge-vertex operator to map.
    
    Returns:
        The mapped majorana operator.
    
    Definition
    ==========
    
    This function decomposes the edge-vertex operators in terms of the majorana operators as
    defined :ref:`here <EdgeVertexOperator-definition>`.
    
    Usage
    =====
    
    .. doctest::
    
        >>> from qiskit_fermions.mappers.library import edge_vertex_to_majorana
        >>> from qiskit_fermions.operators import EdgeVertexOperator
        >>> inter_op = EdgeVertexOperator.from_dict({((0, 0),): 1, ((1, 2),): 2})
        >>> maj_op = edge_vertex_to_majorana(inter_op)
        >>> print(format(maj_op.normal_ordered().simplify()))
          0.000000e0 +1.000000e0j * (γ'0 γ0)
          0.000000e0 +2.000000e0j * (γ2 γ1)
    
    ..
    """

