# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "FCIDump",
]

@typing.final
class FCIDump:
    r"""
    An electronic structure Hamiltonian in FCIDump format.
    
    Definition
    ==========
    
    The FCIDump format was originally defined by Knowles and Handy, 1989 [1]_.
    It is a widespread format for exporting electronic structure Hamiltonians in a plain-text file.
    
    The present data structure only stores the information relevant for constructing the second
    quantized operator.
    However, this implementation goes beyond the original definition by supporting unrestricted
    spin data to be loaded. The table below outlines how integrals are associated with spin species
    based on the intervals in which the indices fall (assuming a header with ``NORB=n``):
    
    ================== ================ ================ ================ ================
    Integral Type      i                j                k                l
    ================== ================ ================ ================ ================
    Constant           :math:`{0}`      :math:`{0}`      :math:`{0}`      :math:`{0}`
    1-body alpha       :math:`{0}`      :math:`{0}`      :math:`[1,n]`    :math:`[1,n]`
    1-body beta        :math:`{0}`      :math:`{0}`      :math:`[n+1,2n]` :math:`[n+1,2n]`
    2-body alpha-alpha :math:`[1,n]`    :math:`[1,n]`    :math:`[1,n]`    :math:`[1,n]`
    2-body alpha-beta  :math:`[1,n]`    :math:`[1,n]`    :math:`[n+1,2n]` :math:`[n+1,2n]`
    2-body beta-beta   :math:`[n+1,2n]` :math:`[n+1,2n]` :math:`[n+1,2n]` :math:`[n+1,2n]`
    ================== ================ ================ ================ ================
    
    The only required values are the 1-body alpha-spin integrals.
    
    The two-body integrals are expected in `chemist` ordering, :math:`(ij|kl)`, matching the FCIDump
    convention.
    
    .. note::
       The implementation of this data structure is opaque to Python and only provides a few
       attributes and methods documented at the end of this page.
    
    Conversion
    ==========
    
    Operator implementations which can be constructed from an instance of :class:`.FCIDump` provide
    a ``from_fcidump`` classmethod:
    
    .. table::
    
      ===================================== =================================================================
      :meth:`.FermionOperator.from_fcidump` Constructs a :class:`.FermionOperator` from an :class:`.FCIDump`.
      ===================================== =================================================================
    
    .. [1] P. J. Knowles and N. C. Handy, Computer Physics Communications 54 (1989) 75-83.
    """
    @property
    def norb(self) -> builtins.int:
        r"""
        Returns the number of orbitals.
        
        This number, :math:`n`, is extracted from the ``NORB=n`` field in the header of the FCIDump
        file.
        """
    @property
    def nelec(self) -> builtins.int:
        r"""
        Returns the number of electrons.
        
        This number is extracted from the ``NELEC`` field in the header of the FCIDump file.
        """
    @property
    def ms2(self) -> builtins.int:
        r"""
        Returns twice the spin quantum number, :math:`2S`.
        
        This number, :math:`2S`, is extracted from the ``MS2=2S`` field in the header of the FCIDump
        file.
        """
    @classmethod
    def from_file(cls, file_path: builtins.str) -> FCIDump:
        r"""
        Parses an FCIDump file.
        
        Assuming you have an FCIDump file called ``molecule.fcidump``, you use this method like so:
        
        .. code-block:: python
        
           from qiskit_fermions.operators.library import FCIDump
        
           fcidump = FCIDump.from_file("molecule.fcidump")
        
        Args:
            file_path: the path to the FCIDump file.
        
        Returns:
            The constructed data structure.
        """

