# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import qiskit.quantum_info
from qiskit_fermions._lib.mappers import ternary_tree_structures
from qiskit_fermions._lib.operators import edge_vertex_operator
from qiskit_fermions._lib.operators import fermion_operator
from qiskit_fermions._lib.operators import majorana_operator
from qiskit_fermions._lib.operators import transfer_vertex_operator
__all__ = [
    "edge_vertex_ternary_tree",
    "fermion_ternary_tree",
    "majorana_ternary_tree",
    "transfer_vertex_ternary_tree",
]

def edge_vertex_ternary_tree(op: edge_vertex_operator.EdgeVertexOperator, encoding: ternary_tree_structures.TernaryTreeEncoding, num_qubits: builtins.int) -> qiskit.quantum_info.SparseObservable:
    r"""
    Map an :class:`.EdgeVertexOperator` to a :class:`~qiskit.quantum_info.SparseObservable` under a
    ternary-tree encoding.
    
    Args:
        op: the edge-vertex operator to map.
        encoding: the compiled encoding to map through.
        num_qubits: the number of qubits for the resulting qubit operator. Must be at least the
            encoding's mode count; a larger value pads with the identity.
    
    Returns:
        The mapped qubit operator, subject to the same simplification and grouping caveats as
        :func:`.fermion_ternary_tree`.
    
    Raises:
        ValueError: if ``op`` acts on a mode the encoding does not cover.
    
    Note:
        Unlike under Jordan-Wigner, a vertex operator is not in general the weight-1 Pauli
        :math:`Z_l`: that is a property of the chain, where the two Majorana strings' :math:`Z` chains
        cancel. On the balanced tree at :math:`n = 4` a vertex operator has weight 3.
    """

def fermion_ternary_tree(op: fermion_operator.FermionOperator, encoding: ternary_tree_structures.TernaryTreeEncoding, num_qubits: builtins.int) -> qiskit.quantum_info.SparseObservable:
    r"""
    Map a :class:`.FermionOperator` to a :class:`~qiskit.quantum_info.SparseObservable` under a
    ternary-tree encoding.
    
    Args:
        op: the fermionic operator to map.
        encoding: the compiled encoding to map through.
        num_qubits: the number of qubits for the resulting qubit operator. Must be at least the
            encoding's mode count; a larger value pads with the identity.
    
    Returns:
        The mapped qubit operator. The result is `not` guaranteed to be fully simplified; call
        :meth:`~qiskit.quantum_info.SparseObservable.simplify` to combine any remaining duplicate
        terms. Duplicates are merged as the result is assembled, to bound the memory required, so the
        exact number of terms returned may vary with the number of threads used. Any grouping carried
        by ``op`` is not reflected in the result, as a
        :class:`~qiskit.quantum_info.SparseObservable` does not track groups.
    
    Raises:
        ValueError: if ``op`` acts on a mode the encoding does not cover.
    
    Usage
    =====
    
    On a chain along ``Z`` this reproduces :func:`.fermion_jordan_wigner` exactly:
    
    .. doctest::
    
        >>> from qiskit_fermions.mappers import TernaryTree, TernaryTreeEncoding
        >>> from qiskit_fermions.mappers.library import (
        ...     fermion_jordan_wigner, fermion_ternary_tree,
        ... )
        >>> from qiskit_fermions.operators import FermionOperator
        >>> fop = FermionOperator.from_dict({((True, 0), (False, 0)): 0.1})
        >>> enc = TernaryTreeEncoding(TernaryTree.chain(2, "Z"))
        >>> fermion_ternary_tree(fop, enc, 2).simplify()
        <SparseObservable with 2 terms on 2 qubits: (0.05+0j)() + (-0.05+0j)(Z_0)>
        >>> bool((fermion_ternary_tree(fop, enc, 2) - fermion_jordan_wigner(fop, 2)).simplify().num_terms == 0)
        True
    
    Other trees trade that encoding's Pauli weight, linear in the number of modes, for a shallower one.
    """

def majorana_ternary_tree(op: majorana_operator.MajoranaOperator, encoding: ternary_tree_structures.TernaryTreeEncoding, num_qubits: builtins.int) -> qiskit.quantum_info.SparseObservable:
    r"""
    Map a :class:`.MajoranaOperator` to a :class:`~qiskit.quantum_info.SparseObservable` under a
    ternary-tree encoding.
    
    Each Majorana operator's image is a single Pauli string, whatever the tree, so a term that is a
    product of several of them composes those strings rather than inflating into a sum.
    
    Args:
        op: the Majorana operator to map.
        encoding: the compiled encoding to map through.
        num_qubits: the number of qubits for the resulting qubit operator. Must be at least the
            encoding's mode count; a larger value pads with the identity.
    
    Returns:
        The mapped qubit operator, subject to the same simplification and grouping caveats as
        :func:`.fermion_ternary_tree`.
    
    Raises:
        ValueError: if ``op`` acts on a mode the encoding does not cover. Note that Majorana index
            :math:`m` acts on mode :math:`\lfloor m/2 \rfloor`.
    
    Usage
    =====
    
    .. doctest::
    
        >>> from qiskit_fermions.mappers import TernaryTree, TernaryTreeEncoding
        >>> from qiskit_fermions.mappers.library import majorana_ternary_tree
        >>> from qiskit_fermions.operators import MajoranaOperator
        >>> mop = MajoranaOperator.from_dict({(0, 1): 1.0})
        >>> enc = TernaryTreeEncoding(TernaryTree.breadth_first(2, 3))
        >>> majorana_ternary_tree(mop, enc, 2).simplify()
        <SparseObservable with 1 term on 2 qubits: (0+1j)(Z_1 Z_0)>
    
    Note that the product of two Majorana strings carries a phase that depends on how their paths
    overlap, and so on the tree.
    """

def transfer_vertex_ternary_tree(op: transfer_vertex_operator.TransferVertexOperator, encoding: ternary_tree_structures.TernaryTreeEncoding, num_qubits: builtins.int) -> qiskit.quantum_info.SparseObservable:
    r"""
    Map a :class:`.TransferVertexOperator` to a :class:`~qiskit.quantum_info.SparseObservable` under a
    ternary-tree encoding.
    
    Args:
        op: the transfer-vertex operator to map.
        encoding: the compiled encoding to map through.
        num_qubits: the number of qubits for the resulting qubit operator. Must be at least the
            encoding's mode count; a larger value pads with the identity.
    
    Returns:
        The mapped qubit operator, subject to the same simplification and grouping caveats as
        :func:`.fermion_ternary_tree`.
    
    Raises:
        ValueError: if ``op`` acts on a mode the encoding does not cover.
    """

