# This code is a Qiskit project.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# ruff: noqa: D205,D212,D415
"""
=================
Operator Grouping
=================

.. currentmodule:: qiskit_fermions.operators.grouping

Overview
--------

The operator representations provided by the :mod:`~qiskit_fermions.operators` module provide a
``groups`` attribute which can optionally be used to specify `group indices` for each term.

What this means concretely, is that all the terms of an operator can be associated with an integer
value and terms with identical indices are considered to be part of the same `group` of terms.
Grouping information provided like this can be exploited in different processing steps, some
examples of which include:

- optimizing the time evolution of an operator with grouped terms

  .. hint::
     A tutorial for this will be provided soon!

- more physically meaningful circuits generated by the :ref:`SqDRIFT routine <sqdrift_tutorial>`

- the selection of `flow sets` [1]_

Usage
-----

The simplest way of defining an operator grouping is by setting the ``groups`` attribute of the
target operator. Below we give a simple example for grouping terms according to the `line flow sets`
as shown in Fig. 1c of [1]_.

.. plot::
   :alt: A simple directed graph on which we define our MajoranaOperator.
   :context: close-figs
   :include-source:

    >>> import rustworkx as rx
    >>> graph = rx.PyDiGraph()
    >>> _ = graph.add_nodes_from(range(6))
    >>> edges = [(0, 1), (1, 2), (3, 0), (1, 4), (5, 2), (5, 4), (4, 3)]
    >>> groups = [0, 0, 1, 2, 1, 3, 3]
    >>> edges_with_group_as_payload = [(i, j, g) for (i, j), g in zip(edges, groups)]
    >>> _ = graph.add_edges_from(edges_with_group_as_payload)
    >>> rx.visualization.mpl_draw(
    ...     graph,
    ...     pos={i: (i % 3, i // 3) for i in range(6)},
    ...     edge_labels=str,
    ...     with_labels=True,
    ... )
    <Figure size 640x480 with 1 Axes>

Here, we have a simple 2 by 3 lattice of Majorana modes which are connected with directional
information. We want to group the corresponding operator terms according to their edge labels.
The code below shows have that can be done:

.. plot::
   :context: close-figs
   :nofigs:
   :include-source:

    >>> from qiskit_fermions.operators import MajoranaOperator
    >>> op = MajoranaOperator(
    ...     [1.0] * 7,
    ...     [node for edge in edges for node in edge],
    ...     [0, 2, 4, 6, 8, 10, 12, 14],
    ... )
    >>> op.groups = groups
    >>> groups = op.split_out_groups()
    >>> for i, g in enumerate(groups):
    ...     print(f"{i}: {list(sorted(g.iter_terms()))}")
    0: [([0, 1], (1+0j)), ([1, 2], (1+0j))]
    1: [([3, 0], (1+0j)), ([5, 2], (1+0j))]
    2: [([1, 4], (1+0j))]
    3: [([4, 3], (1+0j)), ([5, 4], (1+0j))]


.. [1] A. Gandon et al., Stabilizer-based quantum simulation of fermion dynamics with local qubit
       encodings, `arXiv:2512.11418v2 <https://arxiv.org/abs/2512.11418v2>`_.

Library
-------

Rather than always relying on the user to provide the group indices themselves, this module provides
a collection of functions which determine the grouping information automatically.

.. autosummary::
   :toctree: ../stubs/

   group_terms_by_electronic_structure
"""

from qiskit_fermions._lib.operators.operators_grouping.electronic_structure import (
    group_terms_by_electronic_structure,
)

__all__ = [
    "group_terms_by_electronic_structure",
]
