# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "double_factorized_2body",
    "double_factorized_t2",
    "double_factorized_t2_alpha_beta",
    "reconstruct_t2",
    "reconstruct_t2_alpha_beta",
]

def double_factorized_2body(two_body_tensor: numpy.typing.NDArray[numpy.float64], tol: builtins.float, max_vecs: typing.Optional[builtins.int] = None, cholesky: builtins.bool = True) -> builtins.list[tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.complex128]]]:
    r"""
    Double-factorized decomposition of a real two-body tensor.
    
    Represents
    :math:`h_{pqrs} = \sum_t \sum_{kl} Z^{(t)}_{kl} U^{(t)}_{pk} U^{(t)}_{qk} U^{(t)}_{rl} U^{(t)}_{sl}`,
    returning a list of :math:`(Z, U)` terms where each :math:`Z` is a real symmetric diagonal
    Coulomb matrix and each :math:`U` is a unitary orbital rotation.
    
    When ``cholesky`` is ``True`` (the default behavior) the outer factorization uses a modified
    Cholesky decomposition; otherwise it uses a truncated eigendecomposition.
    
    Args:
        two_body_tensor: the real two-body tensor of shape ``(norb, norb, norb, norb)``, in
            `chemist` ordering :math:`(pq|rs)` (i.e. the index pairs :math:`(p,q)` and :math:`(r,s)`
            each label a charge density, as in the reconstruction formula above).
        tol: the tolerance controlling the truncation error of the decomposition.
        max_vecs: the maximum number of terms to retain. Defaults to ``norb * (norb + 1) / 2``.
        cholesky: whether to use the modified Cholesky decomposition (``True``) or a truncated
            eigendecomposition (``False``) for the outer factorization.
    
    Returns:
        A list of :math:`(Z, U)` 2-tuples, where ``Z`` is the diagonal Coulomb matrix and ``U`` is
        the orbital rotation.
    """

def double_factorized_t2(t2_amplitudes: numpy.typing.NDArray[numpy.complex128], tol: builtins.float, max_terms: typing.Optional[builtins.int] = None) -> builtins.list[tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.complex128]]]:
    r"""
    Double-factorized decomposition of spin-restricted :math:`t_2` amplitudes.
    
    Factorizes :math:`t_{ijab}` (with :math:`i, j` occupied and :math:`a, b` virtual) into a list of
    :math:`(Z, U)` terms suitable for reconstruction by :func:`reconstruct_t2`. The number of terms
    is truncated to ``max_terms`` (default: all).
    
    Args:
        t2_amplitudes: the :math:`t_2` amplitudes of shape ``(nocc, nocc, nvrt, nvrt)``.
        tol: the tolerance controlling the truncation error of the decomposition.
        max_terms: the maximum number of terms to retain. Defaults to all.
    
    Returns:
        A list of :math:`(Z, U)` 2-tuples, where ``Z`` is the diagonal Coulomb matrix and ``U`` is
        the orbital rotation.
    """

def double_factorized_t2_alpha_beta(t2_amplitudes: numpy.typing.NDArray[numpy.complex128], tol: builtins.float, max_terms: typing.Optional[builtins.int] = None) -> builtins.list[tuple[builtins.list[numpy.typing.NDArray[numpy.float64]], builtins.list[numpy.typing.NDArray[numpy.complex128]]]]:
    r"""
    Double-factorized decomposition of alpha-beta (spin-unrestricted) :math:`t_2` amplitudes.
    
    Returns a list of terms suitable for reconstruction by :func:`reconstruct_t2_alpha_beta`. The
    number of terms is truncated to ``max_terms`` (default: all).
    
    Args:
        t2_amplitudes: the alpha-beta :math:`t_2` amplitudes of shape
            ``(nocc_a, nocc_b, nvrt_a, nvrt_b)``.
        tol: the tolerance controlling the truncation error of the decomposition.
        max_terms: the maximum number of terms to retain. Defaults to all.
    
    Returns:
        A list of 2-tuples, each consisting of
    
        * a 3-tuple of the diagonal Coulomb matrices in the order ``(aa, ab, bb)``
        * a 2-tuple of the orbital rotations in the order ``(alpha, beta)``
    """

def reconstruct_t2(terms: typing.Sequence[tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.complex128]]], nocc: builtins.int) -> numpy.typing.NDArray[numpy.complex128]:
    r"""
    Reconstructs spin-restricted :math:`t_2` amplitudes from a double-factorized decomposition.
    
    Computes
    :math:`i \sum_k \sum_{pq} Z^{(k)}_{pq} U^{(k)}_{ap} U^{(k)*}_{ip} U^{(k)}_{bq} U^{(k)*}_{jq}`
    and slices to the occupied/virtual block ``[:nocc, :nocc, nocc:, nocc:]``.
    
    Args:
        terms: the list of :math:`(Z, U)` 2-tuples produced by :func:`double_factorized_t2`.
        nocc: the number of occupied orbitals.
    
    Returns:
        The reconstructed :math:`t_2` amplitudes of shape ``(nocc, nocc, nvrt, nvrt)``.
    """

def reconstruct_t2_alpha_beta(terms: typing.Sequence[tuple[typing.Sequence[numpy.typing.NDArray[numpy.float64]], typing.Sequence[numpy.typing.NDArray[numpy.complex128]]]], norb: builtins.int, nocc_a: builtins.int, nocc_b: builtins.int) -> numpy.typing.NDArray[numpy.complex128]:
    r"""
    Reconstructs alpha-beta :math:`t_2` amplitudes from a double-factorized decomposition.
    
    Args:
        terms: the list of terms produced by :func:`double_factorized_t2_alpha_beta`, each a 2-tuple
            of the ``(aa, ab, bb)`` diagonal Coulomb matrices and the ``(alpha, beta)`` orbital
            rotations.
        norb: the number of orbitals.
        nocc_a: the number of alpha-occupied orbitals.
        nocc_b: the number of beta-occupied orbitals.
    
    Returns:
        The reconstructed alpha-beta :math:`t_2` amplitudes of shape
        ``(nocc_a, nocc_b, nvrt_a, nvrt_b)``.
    """

