// This code is a Qiskit project.
//
// (C) Copyright IBM 2026.
//
// This code is licensed under the Apache License, Version 2.0. You may
// obtain a copy of this license in the LICENSE.txt file in the root directory
// of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.

use std::{fs::File, io::Write, str::FromStr};

extern crate cbindgen;

/// This function generates the C header from the qiskit-fermions-cext crate.
fn generate_header() {
    // If changing the files generated by this build script, make sure to update the
    // `C_INCLUDE_FILES_GENERATED` variable in the top-level Makefile too.

    // Trigger this script if the header was changed/removed.
    #![allow(clippy::print_stdout)]
    println!("cargo:rerun-if-changed=../../target/qiskit_fermions.h");

    // Pull the config from the cbindgen.toml file.
    let config = cbindgen::Config::from_file("cbindgen.toml").unwrap();

    // Ensure target path exists and then set the full filename of qiskit_fermions.h.
    let mut path = ::std::path::PathBuf::from_str("../../target/").unwrap();
    ::std::fs::create_dir_all(&path).expect("Could not create target directory.");
    path.push("qiskit_fermions.h");

    // Build the header.
    let mut buffer: Vec<u8> = Vec::new();
    cbindgen::Builder::new()
        .with_crate(".")
        .with_config(config)
        .generate()
        .expect("Unable to generate C bindings.")
        .write(&mut buffer);

    let header = String::from_utf8(buffer).expect("Unable to parse C bindings.");

    // When writing the header, we're checking that all bytes have been written.
    let mut header_file = File::create(&path).expect("The qiskit_fermions.h path should exist.");
    let header_bytes = header.as_bytes();
    let expected_bytes_written = header_bytes.len();
    let bytes_written = header_file
        .write(header.as_bytes())
        .expect("Unable to write header.");
    if bytes_written != expected_bytes_written {
        panic!("Unable to write header (partial write detected).");
    }
}

fn main() {
    generate_header();
}
