# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from qiskit_fermions._lib.operators import fermion_operator
from qiskit_fermions._lib.operators import majorana_operator
__all__ = [
    "fermion_to_majorana",
    "majorana_to_fermion",
]

def fermion_to_majorana(fer_op: fermion_operator.FermionOperator) -> majorana_operator.MajoranaOperator:
    r"""
    Map a :class:`.FermionOperator` to a :class:`.MajoranaOperator`.
    
    Args:
        fer_op: the fermionic operator to map.
    
    Returns:
        The mapped majorana operator.
    
    Definition
    ==========
    
    This function implements the simple transformation:
    
    .. math::
    
       a^\dagger_j \rightarrow \frac{1}{2} (\gamma_j - i \gamma'_j) ~~\text{and}~~
       a_j \rightarrow \frac{1}{2} (\gamma_j + i \gamma'_j)
    
    where :math:`a^\dagger_j` (:math:`a_j`) is the fermionic creation (annihilation) operator
    acting on the :math:`j`-th spin-less fermionic mode, and :math:`\gamma_j`/:math:`\gamma'_j` are
    the two Majorana fermion operators. In the case of the :class:`.MajoranaOperator` these will be
    stored on the even and odd Majorana modes, respectively.
    
    Usage
    =====
    
    .. doctest::
    
        >>> from qiskit_fermions.mappers.library import fermion_to_majorana
        >>> from qiskit_fermions.operators import FermionOperator
        >>> fer_op = FermionOperator.from_dict({((True, 0), (False, 0)): 1})
        >>> maj_op = fermion_to_majorana(fer_op)
        >>> print(format(maj_op.normal_ordered().simplify()))
         5.000000e-1 +0.000000e0j * ()
         0.000000e0-5.000000e-1j * (γ'0 γ0)
    
    ..
    """

def majorana_to_fermion(maj_op: majorana_operator.MajoranaOperator) -> fermion_operator.FermionOperator:
    r"""
    Map a :class:`.MajoranaOperator` to a :class:`.FermionOperator`.
    
    Args:
        maj_op: the Majorana operator to map.
    
    Returns:
        The mapped fermion operator.
    
    Definition
    ==========
    
    This function implements the simple transformation:
    
    .. math::
    
       \gamma_j \rightarrow a^\dagger_j + a_j ~~\text{and}~~
       \gamma'_j \rightarrow i (a^\dagger_j - a_j)
    
    where :math:`\gamma_j`/:math:`\gamma'_j` are the two Majorana fermion operators (stored on the
    even and odd modes, respectively), and :math:`a^\dagger_j` (:math:`a_j`) is the fermionic
    creation (annihilation) operator acting on the :math:`j`-th spin-less fermionic mode.
    
    Usage
    =====
    
    .. doctest::
    
        >>> from qiskit_fermions.mappers.library import majorana_to_fermion
        >>> from qiskit_fermions.operators import MajoranaOperator
        >>> maj_op = MajoranaOperator.from_dict({(0, 1): 1})
        >>> fer_op = majorana_to_fermion(maj_op)
        >>> print(format(fer_op.normal_ordered().simplify()))
         0.000000e0 +1.000000e0j * ()
         0.000000e0 -2.000000e0j * (+0 -0)
    
    ..
    """

