# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "FciLinearOperator",
    "slater_determinant_statevector",
]

@typing.final
class FciLinearOperator:
    r"""
    A minimal, native `scipy.sparse.linalg.LinearOperator`-compatible view of an operator restricted
    to a fixed FCI sector.
    
    This class duck-types the subset of the SciPy ``LinearOperator`` interface that
    :func:`scipy.sparse.linalg.expm_multiply` requires: it exposes :attr:`shape`, :attr:`dtype`,
    :meth:`matvec`, and :meth:`rmatvec`. (``expm_multiply`` needs the adjoint action -- ``rmatvec``
    -- because its internal one-norm estimator operates on ``A.H``.) It is **not** part of the public
    API; it is an internal wrapper returned by the ``_linear_operator_`` protocol methods on the
    operator classes and consumed by the simulation path.
    """
    @property
    def shape(self) -> tuple[builtins.int, builtins.int]:
        r"""
        The shape of the operator as a square ``(dim, dim)`` tuple.
        """
    @property
    def dtype(self) -> typing.Any:
        r"""
        The dtype of the operator, always ``numpy.dtype("complex128")``.
        """
    def matvec(self, vec: numpy.typing.NDArray[numpy.complex128]) -> numpy.typing.NDArray[numpy.complex128]:
        r"""
        Applies the operator to a state vector: returns ``op @ vec``.
        
        Args:
            vec: the input state vector, a contiguous one-dimensional ``complex128`` array of length
                ``dim``.
        
        Returns:
            The transformed state vector of length ``dim``.
        
        Raises:
            ValueError: if ``vec`` has the wrong length, or the underlying operator acts on a mode
                index outside the sector.
        """
    def rmatvec(self, vec: numpy.typing.NDArray[numpy.complex128]) -> numpy.typing.NDArray[numpy.complex128]:
        r"""
        Applies the operator's adjoint to a state vector: returns ``op.H @ vec``.
        
        SciPy's ``expm_multiply`` requires this because its one-norm estimator operates on ``A.H``.
        
        Args:
            vec: the input state vector, a contiguous one-dimensional ``complex128`` array of length
                ``dim``.
        
        Returns:
            The adjoint-transformed state vector of length ``dim``.
        
        Raises:
            ValueError: if ``vec`` has the wrong length, or the underlying operator acts on a mode
                index outside the sector.
        """

def slater_determinant_statevector(norb: builtins.int, alpha_str: builtins.int, beta_str: typing.Optional[builtins.int] = None) -> numpy.typing.NDArray[numpy.complex128]:
    r"""
    Builds the FCI state vector of a single occupation determinant.
    
    This is the state-vector seed a Jordan-Wigner occupation prepares from the vacuum, produced
    directly in the FCI basis ordering (the same ordering the matvec kernels and ``ffsim`` use). The
    occupied orbitals of each spin sector are passed as bitmasks (bit ``p`` set iff orbital ``p`` is
    occupied).
    
    Args:
        norb: the number of spatial orbitals.
        alpha_str: the occupation bitmask of the alpha sector (or of the single spinless sector).
        beta_str: the occupation bitmask of the beta sector, or ``None`` for a spinless system. When
            ``None`` the returned vector has length ``C(norb, popcount(alpha_str))``; otherwise it has
            length ``C(norb, popcount(alpha_str)) * C(norb, popcount(beta_str))`` with the block-spin
            flat index ``addr_a * dim_b + addr_b``.
    
    Returns:
        The one-hot Slater-determinant state vector as a ``complex128`` array.
    
    Raises:
        ValueError: if ``norb`` exceeds the maximum number of orbitals the bitmask representation
            supports (64), an occupation bit is set outside ``0..norb``, or the spinful FCI
            dimension overflows the addressable range.
    """

