# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from qiskit_fermions._lib.operators import edge_vertex_operator
from qiskit_fermions._lib.operators import fermion_operator
from qiskit_fermions._lib.operators import majorana_operator
from qiskit_fermions._lib.operators import transfer_vertex_operator
__all__ = [
    "transfer_vertex_to_edge_vertex",
    "transfer_vertex_to_fermion",
    "transfer_vertex_to_majorana",
]

def transfer_vertex_to_edge_vertex(inter_op: transfer_vertex_operator.TransferVertexOperator) -> edge_vertex_operator.EdgeVertexOperator:
    r"""
    Map a :class:`.TransferVertexOperator` to an :class:`.EdgeVertexOperator`.
    
    Args:
        inter_op: the transfer-vertex operator to map.
    
    Returns:
        The mapped edge-vertex operator.
    
    Definition
    ==========
    
    This function decomposes the transfer-vertex operators in terms of the edge-vertex operators as
    defined :ref:`here <TransferVertexOperator-definition>`.
    
    Usage
    =====
    
    .. doctest::
    
        >>> from qiskit_fermions.mappers.library import transfer_vertex_to_edge_vertex
        >>> from qiskit_fermions.operators import TransferVertexOperator
        >>> dir_op = TransferVertexOperator.from_dict({((0, 0),): 1, ((1, 2),): 2, ((2, 1),): -2})
        >>> undir_op = transfer_vertex_to_edge_vertex(dir_op)
        >>> print(format(undir_op.simplify()))
          1.000000e0 +0.000000e0j * (V(0))
          0.000000e0 +1.000000e0j * (V(1) E(1,2))
         -0.000000e0 -1.000000e0j * (E(1,2) V(2))
    
    ..
    """

def transfer_vertex_to_fermion(inter_op: transfer_vertex_operator.TransferVertexOperator) -> fermion_operator.FermionOperator:
    r"""
    Map a :class:`.TransferVertexOperator` to a :class:`.FermionOperator`.
    
    Args:
        inter_op: the transfer-vertex operator to map.
    
    Returns:
        The mapped fermionic operator.
    
    Definition
    ==========
    
    This function decomposes the transfer-vertex operators in terms of the fermionic action
    operators as defined :ref:`here <TransferVertexOperator-definition>`.
    
    Usage
    =====
    
    .. doctest::
    
        >>> from qiskit_fermions.mappers.library import transfer_vertex_to_fermion
        >>> from qiskit_fermions.operators import TransferVertexOperator
        >>> inter_op = TransferVertexOperator.from_dict({((0, 0),): 1, ((1, 2),): 2, ((2, 1),): -2})
        >>> fer_op = transfer_vertex_to_fermion(inter_op)
        >>> print(format(fer_op.normal_ordered().simplify()))
          1.000000e0 +0.000000e0j * ()
         -2.000000e0 +0.000000e0j * (-2 -1)
         -2.000000e0 +0.000000e0j * (+0 -0)
          2.000000e0 -0.000000e0j * (+2 +1)
    
    ..
    """

def transfer_vertex_to_majorana(inter_op: transfer_vertex_operator.TransferVertexOperator) -> majorana_operator.MajoranaOperator:
    r"""
    Map a :class:`.TransferVertexOperator` to a :class:`.MajoranaOperator`.
    
    Args:
        inter_op: the transfer-vertex operator to map.
    
    Returns:
        The mapped majorana operator.
    
    Definition
    ==========
    
    This function decomposes the transfer-vertex operators in terms of the majorana operators as
    defined :ref:`here <TransferVertexOperator-definition>`.
    
    Usage
    =====
    
    .. doctest::
    
        >>> from qiskit_fermions.mappers.library import transfer_vertex_to_majorana
        >>> from qiskit_fermions.operators import TransferVertexOperator
        >>> inter_op = TransferVertexOperator.from_dict({((0, 0),): 1, ((1, 2),): 2, ((2, 1),): -2})
        >>> maj_op = transfer_vertex_to_majorana(inter_op)
        >>> print(format(maj_op.normal_ordered().simplify()))
          0.000000e0 +1.000000e0j * (γ'0 γ0)
         -0.000000e0 -1.000000e0j * (γ2 γ'1)
         -0.000000e0 -1.000000e0j * (γ'2 γ1)
    
    ..
    """

