name: Lint

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  # Only cancel in PR mode, otherwise we may have weird half-uploaded docs...
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    if: github.repository_owner == 'Qiskit'
    name: lint check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        name: Install Python
        with:
          python-version: '3.10'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install dependencies
        run: |
            python -m pip install -U pip tox
            sudo apt-get install -y clang-format

      - name: Generate qiskit-pyo3-ffi crate
        shell: bash
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git clone https://github.com/Qiskit/qiskit build/qiskit
          cd build/qiskit
          # checkout the latest (i.e. stable) release tag
          git checkout $(gh release -R Qiskit/qiskit view 2.5.0rc1 --json tagName --jq ".tagName")
          make qiskit-pyo3-ffi
          # ad-hoc workaround until a proper solution is found for
          # `qiskit-pyo3-ffi` being nested in our workspace folder
          sed -i.bak '/\[workspace\]/d' dist/rust/qiskit-pyo3-ffi/Cargo.toml

      - name: Install Package
        shell: bash
        run: |
          pip install --pre qiskit
          pip install --group build --group lint
          SETUPTOOLS_RUST_CARGO_PROFILE=release pip install --no-build-isolation -e ".[all]"

      - name: Run lint check
        shell: bash
        run: |
          make lint
